const fs=require('fs'),path=require('path'),{sceneSVG}=require('./assets/scene.js');
fs.mkdirSync(__dirname+'/svg',{recursive:true});
for(let i=0;i<288;i++)fs.writeFileSync(__dirname+'/svg/'+String(i).padStart(4,'0')+'.svg',sceneSVG(i/24));
console.log('Exported 288 SVG frames');
const scene=fs.readFileSync(__dirname+'/assets/scene.js','utf8');
const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#08121c"><title>منتصف الليل | MIDNIGHT</title><style>*{box-sizing:border-box}body{margin:0;background:#060d17;color:#dceae8;font-family:system-ui,sans-serif;min-height:100vh;display:grid;place-items:center;padding:32px}main{width:min(1280px,100%)}header{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:20px}h1{font-size:24px;font-weight:600;margin:0 0 7px}p{font-size:12px;line-height:1.6;color:#81a2ab;margin:0}.brand{direction:ltr;letter-spacing:4px;font-size:10px;color:#69c8c8}#stage{aspect-ratio:16/9;overflow:hidden;border:1px solid #21414c;box-shadow:0 30px 90px #0007;border-radius:12px;background:#07121d}svg{display:block;width:100%;height:auto}footer{display:flex;align-items:center;gap:14px;margin-top:19px}button,a{border-radius:30px;border:1px solid #35535b;color:#cce7df;background:#0f242c;padding:11px 20px;font:inherit;font-size:12px;text-decoration:none;cursor:pointer}button:hover,a:hover{background:#194049}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #ffb769;outline-offset:4px}input{flex:1;direction:ltr;min-width:40px;accent-color:#71e5d2}small{direction:ltr;font-size:12px;white-space:nowrap;color:#8fadb6}.note{margin-top:16px;color:#688c98;font-size:11px}.capture{display:block;padding:0}.capture main{width:1280px}.capture header,.capture footer,.capture .note{display:none}.capture #stage{border:0;border-radius:0;box-shadow:none}@media(max-width:620px){body{padding:12px}header{align-items:start}.brand{font-size:8px;letter-spacing:2px}h1{font-size:18px}footer{gap:8px;flex-wrap:wrap}button,a{padding:10px 14px}.note{line-height:1.8}}</style></head><body><main><header><div><h1>منتصف الليل</h1><p>مدينة نيون، مطر، وقفزة صغيرة نحو الضوء.</p></div><div class="brand">MIDNIGHT / KOSIF MOTION</div></header><div id="stage"></div><footer><button id="play" type="button">إيقاف مؤقت</button><button id="restart" type="button">من البداية</button><input id="time" aria-label="موضع الفيديو" type="range" min="0" max="12" step=".01" value="0"><small id="readout">0.0 / 12.0 s</small><a href="midnight-cat.mp4" download>تنزيل MP4</a></footer><p class="note">مشهد متجهي 2.5D • 12 ثانية • 1280 × 720 • 24 إطارًا/ث • بدون صوت • يعمل دون اتصال أو مكتبات خارجية</p></main><script>${scene}</script><script>
(()=>{const stage=document.getElementById('stage'),slider=document.getElementById('time'),play=document.getElementById('play'),readout=document.getElementById('readout');let playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,current=0,last=null;window.__duration=12;window.__ready=true;window.render=t=>{current=Math.max(0,Math.min(12,Number(t)||0));stage.innerHTML=CinematicCat.sceneSVG(current);slider.value=current;readout.textContent=current.toFixed(1)+' / 12.0 s';};window.setPlaying=v=>{playing=!!v;last=null;play.textContent=playing?'إيقاف مؤقت':'تشغيل';play.setAttribute('aria-label',playing?'إيقاف الحركة':'تشغيل الحركة');};play.onclick=()=>{if(current>=12)window.render(0);window.setPlaying(!playing);};document.getElementById('restart').onclick=()=>{window.render(0);window.setPlaying(true);};slider.oninput=()=>{window.setPlaying(false);window.render(slider.value);};if(new URLSearchParams(location.search).has('capture')){document.body.classList.add('capture');playing=false;}window.setPlaying(playing);window.render(0);function tick(ts){if(playing&&last!==null){window.render(current+Math.min((ts-last)/1000,.1));if(current>=12)window.setPlaying(false);}last=ts;requestAnimationFrame(tick);}requestAnimationFrame(tick);})();
</script></body></html>`;
fs.writeFileSync(__dirname+'/midnight-cat.original.html',html);console.log('Built self-contained HTML player');
