// Mocked-browser lifecycle tests. These do NOT verify real browser encoding or playback.
import test from 'node:test';
import assert from 'node:assert/strict';
let run=0;
async function harness(){
 const downloads=[],recorders=[],tracks=[],elements=new Map(); let frames=[];
 class Element extends EventTarget {constructor(tag='div'){super();this.tagName=tag.toUpperCase();this.children=[];this.style={};this.dataset={};this.value='';this.disabled=false;this.hidden=false;this.className='';this.textContent='';this.classList={toggle(){}};this.width=1280;this.height=720;this.files=[];}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=[...items];}remove(){}setAttribute(k,v){this[k]=v;}getAttribute(k){return this[k];}click(){if(this.tagName==='A')downloads.push(this);this.dispatchEvent(new Event('click'));}getContext(){return new Proxy({createLinearGradient(){return{addColorStop(){}};},createRadialGradient(){return{addColorStop(){}};}},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>{t[k]=v;return true;}});}captureStream(){const t={stopped:false,stop(){this.stopped=true;}};tracks.push(t);return{getTracks:()=>[t],addTrack(){}};}getBoundingClientRect(){return{left:0,top:0,width:1280,height:720};}setPointerCapture(){}}
 class Recorder extends EventTarget {static isTypeSupported(m){return m.startsWith('video/webm');}constructor(stream,options){super();this.state='inactive';this.mimeType=options.mimeType;recorders.push(this);}start(){this.state='recording';}stop(){this.state='inactive';queueMicrotask(()=>{const d=new Event('dataavailable');d.data=new Blob(['encoded-fixture']);this.dispatchEvent(d);this.dispatchEvent(new Event('stop'));});}}
 const document=new EventTarget();document.getElementById=id=>{if(!elements.has(id))elements.set(id,new Element(id==='preview'?'canvas':'button'));return elements.get(id);};document.createElement=tag=>new Element(tag);document.querySelectorAll=()=>[];document.body=new Element('body');document.hidden=false;
 const window=new EventTarget();Object.assign(globalThis,{document,window,MediaRecorder:Recorder,requestAnimationFrame:fn=>frames.push(fn)});globalThis.setTimeout=(fn)=>({unref(){}});globalThis.clearTimeout=()=>{};
 await import(`../../scripts/web/static/studio/app.mjs?mock=${run++}`);
 const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
 return{document,window,el:id=>document.getElementById(id),recorders,tracks,downloads,flush,frame:()=>{const f=frames.shift();f?.(performance.now()+100000);}};
}
test('mock browser: demo initializes and enables supported export',async()=>{const h=await harness();assert.equal(h.el('export').disabled,false);assert.equal(h.el('total-time').textContent,'00:08.0');assert.equal(h.el('clip-track').children.length,1);});
test('mock browser: cancel while export preparation awaits creates no late recorder',async()=>{const h=await harness();h.el('export').click();h.el('cancel-export').click();await h.flush();assert.equal(h.recorders.length,0);assert.equal(h.downloads.length,0);assert.equal(h.el('export-progress').hidden,true);});
test('mock browser: successful recording downloads actual mime extension and stops capture tracks',async()=>{const h=await harness();h.el('export').click();await h.flush();assert.equal(h.recorders.length,1);assert.equal(h.recorders[0].state,'recording');h.frame();await h.flush();assert.equal(h.downloads.length,1);assert.match(h.downloads[0].download,/\.webm$/);assert.equal(h.tracks.every(t=>t.stopped),true);assert.equal(h.el('export-progress').hidden,true);});
test('mock browser: cancel active recording discards chunks and releases tracks',async()=>{const h=await harness();h.el('export').click();await h.flush();h.el('cancel-export').click();await h.flush();assert.equal(h.downloads.length,0);assert.equal(h.tracks.every(t=>t.stopped),true);assert.equal(h.el('export-progress').hidden,true);});
test('mock browser: recorder error never downloads success artifact',async()=>{const h=await harness();h.el('export').click();await h.flush();h.recorders[0].dispatchEvent(new Event('error'));await h.flush();assert.equal(h.downloads.length,0);assert.match(h.el('status').textContent,/خطأ/);assert.equal(h.tracks.every(t=>t.stopped),true);});
test('mock browser: hiding tab aborts export with explicit message',async()=>{const h=await harness();h.el('export').click();await h.flush();h.document.hidden=true;h.document.dispatchEvent(new Event('visibilitychange'));await h.flush();assert.equal(h.downloads.length,0);assert.match(h.el('status').textContent,/الخلفية/);assert.equal(h.tracks.every(t=>t.stopped),true);});
