# -*- coding: utf-8 -*-
"""100 مهارة خارقة — تعريفات المهارات 01–25 (الحركة والصورة والفيديو)."""
A = [
dict(n="01", slug="claude-animation-studio", ar="استوديو الأنيميشن بكلاود", en="Claude Animation Studio",
 desc="يصنع فيديو أنيميشن كامل داخل كلاود بلا أي برنامج مونتاج: من الفكرة إلى DESIGN.md وSTORYBOARD.md، ثم مشهد HTML بخط زمني حتمي render(t)، ثم تصوير الإطارات بـ Playwright وتجميعها بـ ffmpeg مع لوحة تحقق. يدعم 2D (SVG/Canvas) و3D (Three.js) وGSAP، وبنسب 9:16 و16:9 و1:1.",
 trig_ar=["انميشن","أنيميشن","فيديو متحرك","موشن","حركة","اعمل فيديو","ريل متحرك"], trig_en=["animation","animated video","motion video","render frames","make an animation"],
 pipeline=["الإطار: المنصة والنسبة والمدة والجمهور والهدف وخطّاف أول ثانية ونداء الختام.","الهوية البصرية أولاً (بوابة إلزامية): DESIGN.md بلوحة ألوان من 3 إلى 5 ألوان لها أدوار، وخطّ عربي وخطّ لاتيني، وقواعد حركة، وقائمة «ما لا نفعله».","STORYBOARD.md: جدول إيقاعات بأزمنة البداية والنهاية، وما يظهر، والحركة، والتعليق الصوتي المقترح.","التخطيط قبل الحركة: ابنِ إطار البطل لكل مشهد كـ HTML/CSS ثابت، ثم أضف الدخول بـ from والخروج بـ to.","خط زمني واحد حتمي: كل شيء دالة في الزمن render(t)، ولا يقرأ أي عنصر ساعة الجهاز، فيتطابق الفيديو مع المعاينة إطاراً بإطار.","التصوير: scripts/capture.py يصوّر الإطارات بـ Playwright (Edge أو Chromium) بالأبعاد المطلوبة.","التجميع: scripts/encode.py يبني MP4 بـ H.264 وyuv420p ولوحة تحقق contact-sheet.png، ويدمج الصوت إن وُجد.","الفحص: scripts/qa.py يكشف الإطارات السوداء والمتطابقة، ثم مراجعة بصرية للوحة التحقق قبل التسليم."],
 gates=["لا ألوان افتراضية (#333 أو #3b82f6) ولا خطوط محظورة (Inter، Roboto، Poppins).","تنويع التمهيد: ليس كل العناصر تدخل من نفس الاتجاه وبنفس السرعة؛ المشهد الأبطأ 3× من الأسرع.","بنية كل مشهد: بناء 30% ثم تنفّس 40% ثم حسم 30%، والخروج أسرع من الدخول.","نص لا يقل عن 40px على 1080p، وتباين 4.5:1، وزمن قراءة أقل من زمن الظهور."],
 outputs=["DESIGN.md","STORYBOARD.md","index.html (مشهد حي يعمل في المتصفح)","frames/ + <name>.mp4","contact-sheet.png + qa.json"],
 kw=["animation","animate","motion","gsap","remotion","hyperframes","video composition","framer motion","keyframe","lottie","three.js","webgl","title card"], scripts=True),
dict(n="02", slug="trend-animation-styles", ar="أساليب الأنيميشن الترند", en="Trending Animation Styles",
 desc="مكتبة الأساليب الرائجة جاهزة للتنفيذ بكلاود: الكينتك تايبوغرافي، وموشن الواجهات الزجاجية، وLo-fi، والـ Paper cut-out، والـ Isometric، والـ Line-art الذي يرسم نفسه، والـ Data-in-motion، والـ Glitch/Neon، وأسلوب الوثائقيات التوضيحية. لكل أسلوب: لوحة ألوان وخط وقواعد حركة ومقتطف كود.",
 trig_ar=["ستايل انميشن","أسلوب ترند","انميشن زي","كينتك","تايبوغرافي متحركة"], trig_en=["trending animation style","kinetic typography","cut-out animation","isometric animation","line art animation","glitch"],
 pipeline=["حدّد الهدف والمنصة، ثم اختر أسلوباً واحداً من الجدول (أو اثنين متناغمين) واذكر سبب الاختيار.","افتح ورقة الأسلوب: الألوان، والخطوط، والسرعات، والتمهيدات المسموحة، وما يُمنع.","ولّد DESIGN.md من الورقة ثم انتقل إلى claude-animation-studio للتنفيذ.","أضف لمسة الأسلوب في كل مشهد (حبيبات، توهج، خطوط إرشاد، ظلال ورقية) كطبقة خلفية حية.","راجع لوحة التحقق ضد قائمة «علامات التصميم الآلي» وأزلها."],
 gates=["أسلوب واحد مسيطر؛ لا خلط ثلاثة أساليب.","كل مشهد ثلاث طبقات على الأقل: خلفية حية، محتوى، لمسات.","لا تدرّجات بنفسجي-أزرق ولا نيون على أسود إلا إذا كان الأسلوب يطلبها."],
 outputs=["ورقة الأسلوب المختار","DESIGN.md","مقتطفات CSS/GSAP للأسلوب"],
 kw=["motion design","kinetic","typography","awwwards","ui motion","hero animation","scroll animation","parallax","glitch","neon glow","isometric","motion graphics"], scripts=True),
dict(n="03", slug="kinetic-typography-arabic", ar="تايبوغرافي عربية متحركة", en="Arabic Kinetic Typography",
 desc="فيديوهات كلمات متحركة بالعربية (اقتباسات، شعارات، أرقام، كلمات أغانٍ) مع خطوط عربية صحيحة واتجاه RTL وتشكيل سليم، وإيقاع يتبع الكلام أو الموسيقى، بإخراج 9:16 للريلز.",
 trig_ar=["كلمات متحركة","اقتباس متحرك","نص متحرك","تايبوغرافي عربي"], trig_en=["arabic kinetic text","animated quote","lyric video","text animation rtl"],
 pipeline=["النص أولاً: قسّمه إلى وحدات معنى (لا أكثر من 5 كلمات لكل ظهور) وحدّد الكلمة المفتاحية في كل وحدة.","الإيقاع: من الصوت (BPM أو توقيتات الكلام) أو من زمن القراءة (0.35 ثانية للكلمة).","الخط: Cairo أو Tajawal أو Amiri أو Changa بأوزان متباعدة (300 مقابل 900)؛ اختبر التشكيل والكشيدة قبل الحركة.","الحركة: دخول الكلمة المفتاحية بأسلوب مختلف (قياس أو تتبع حروف)، والبقية تلاشٍ هادئ؛ لا تحريك حروف منفصلة في العربية إلا بتقنية mask.","أنتج بـ claude-animation-studio وافحص قطع الحروف المتصلة في لوحة التحقق."],
 gates=["لا تفكيك للحروف العربية المتصلة.","اتجاه الدخول يحترم RTL (من اليمين).","كل كلمة تظهر زمناً كافياً لقراءتها مرتين."],
 outputs=["script.json (الوحدات وأزمنتها)","index.html","mp4 عمودي"],
 kw=["typography","kinetic","text animation","lyrics","captions","arabic","rtl","font"]),
dict(n="04", slug="character-animation-2d", ar="تحريك الشخصيات 2D", en="2D Character Animation",
 desc="شخصيات كرتونية متحركة داخل المتصفح: تصميم الشخصية بأجزاء (rig) من SVG، ودورات المشي والحديث والتعبيرات، ومبادئ الأنيميشن الاثني عشر (الضغط والتمدد، والتوقع، والمتابعة)، وتزامن الشفاه مع الصوت تقريبياً.",
 trig_ar=["شخصية كرتونية","كرتون متحرك","تحريك شخصية","كارتون"], trig_en=["character animation","cartoon character","walk cycle","lip sync","rig"],
 pipeline=["ورقة الشخصية: الشكل الأساسي من دوائر ومستطيلات، والنسب، واللوحة، وثلاث تعبيرات.","Rig بـ SVG: مجموعات <g> لكل جزء بنقطة ارتكاز صحيحة (الكتف، الورك، الرقبة).","دورات الحركة كدوال في الطور: walk(phase)، idle(phase)، talk(phase) بزوايا الأطراف وارتفاع الجسم.","المبادئ: توقع قبل الحركة، ضغط عند الهبوط، متابعة للشعر والملابس، وقوس لكل مسار.","الفم: 6 أشكال (مغلق، A، O، E، M، F) تُختار من طاقة الصوت أو من نص الكلام.","أنتج عبر claude-animation-studio مع خلفية حية بسيطة."],
 gates=["الحجوم ثابتة بين الإطارات (لا رأس يكبر).","وضع التلامس ووضع المرور متمايزان في المشي.","الأطراف منفصلة بصرياً عن الجذع بخط أو لون."],
 outputs=["character.svg","rig.js","index.html + mp4"],
 kw=["character animation","sprite","walk cycle","rigging","cartoon","animate","pixel art","lip sync","svg animation"], neg=("vercel","react")),
dict(n="05", slug="explainer-edu-animation", ar="أنيميشن تعليمي توضيحي", en="Explainer Animation",
 desc="فيديوهات شرح مبسّطة (علوم، تاريخ، اقتصاد، منتجات) بأسلوب مسطّح واضح: فكرة واحدة لكل مشهد، ورسوم تخطيطية تتحرك مع الشرح، وشريط مراحل، وتعليق صوتي مقترح، ودقة علمية مفحوصة.",
 trig_ar=["فيديو تعليمي","شرح متحرك","انميشن تعليمي","درس متحرك"], trig_en=["explainer video","educational animation","whiteboard animation","how it works video"],
 pipeline=["حلّل المفهوم إلى 3 إلى 6 خطوات سببية، واكتب لكل خطوة جملة واحدة.","افحص الدقة: كل ادعاء علمي يُقابل بمصدر أو يُحذف.","مشهد واحد ثابت الكاميرا غالباً، وعنصر واحد يتحرك في كل مرحلة، وشريط مراحل في الأسفل.","التعليق الصوتي: 2.5 كلمة في الثانية، ونصّ على الشاشة أقصر من المنطوق.","أنتج بـ claude-animation-studio ثم اختبر على طالب افتراضي: هل يُعاد شرح الفكرة من الفيديو وحده؟"],
 gates=["لا معلومات علمية خاطئة.","نص واحد لكل مرحلة وبسطر واحد.","تباين 4.5:1 وأحجام 40px فأكثر."],
 outputs=["STORYBOARD.md بالتعليق الصوتي","index.html + mp4","ملخص الدقة العلمية"],
 kw=["explainer","education","teaching","lesson","whiteboard","diagram","infographic","animation"]),
dict(n="06", slug="cinematic-3d-scene", ar="مشهد سينمائي ثلاثي الأبعاد", en="Cinematic 3D Scene",
 desc="مشاهد Three.js سينمائية داخل المتصفح: إضاءة فيزيائية، وBloom وتدرّج ألوان، وضباب وجسيمات، وشيدرات بسيطة، وحركات كاميرا (دخول بطيء، أوربت، كرين)، وبيئات (مدينة، صحراء، فضاء) جاهزة للتصوير إطاراً بإطار.",
 trig_ar=["ثري دي","3D","مشهد سينمائي","three.js","مدينة مستقبلية"], trig_en=["three.js scene","webgl cinematic","3d animation","shader","bloom","orbit camera"],
 pipeline=["مرجعية الإضاءة والألوان: مفتاح واحد واتجاه واحد وكلفن محدد.","الهندسة من بدائيات وInstancedMesh للجموع (مبانٍ، نخيل، نجوم) ببذرة عشوائية ثابتة.","المواد: MeshStandard/Physical مع خريطة بيئة PMREM؛ شيدر مخصص للسماء والماء فقط.","المعالجة اللاحقة: Bloom معتدل، وتدرّج ACES، وفينييت، وحبيبات خفيفة.","الكاميرا دالة في الزمن بمنحنيات ناعمة، وحركة واحدة لكل لقطة.","التصوير بـ preserveDrawingBuffer والتجميع عبر claude-animation-studio."],
 gates=["لا أكثر من 150 ألف مثلث مرئي لثبات التصوير.","اتجاه الضوء ثابت داخل اللقطة.","لا شعارات ولا أشخاص حقيقيين."],
 outputs=["index.html (Three.js)","mp4 + لوحة تحقق","قائمة الأصول والبذور"],
 kw=["three.js","webgl","shader","r3f","3d","postprocessing","particles","glsl","webgpu"]),
dict(n="07", slug="data-in-motion", ar="بيانات متحركة", en="Data in Motion",
 desc="رسوم بيانية متحركة للفيديو والعروض: أعمدة تنمو، وخطوط ترسم نفسها، وأرقام تعدّ، وخرائط تضيء، مع قواعد الوضوح والصدق الإحصائي وتصميم ألوان متاح للجميع.",
 trig_ar=["رسم بياني متحرك","ارقام متحركة","احصائيات فيديو","انفوجرافيك متحرك"], trig_en=["animated chart","data animation","counter animation","animated infographic","dataviz video"],
 pipeline=["البيانات أولاً: جدول CSV نظيف وحساب القيم في الكود لا في النص.","اختر الشكل: مقارنة = أعمدة، اتجاه = خط، نسبة = شريط مكدّس (لا فطيرة متحركة).","ترتيب الظهور بحسب الأهمية، ومحور ثابت لا يتحرك مع البيانات.","الألوان: لوحة فئوية مقروءة لعمى الألوان، ولون تمييز واحد.","أنتج بـ claude-animation-studio وأضف مصدر البيانات في الركن."],
 gates=["المحور يبدأ من صفر للأعمدة.","لا تأثيرات 3D على الرسوم البيانية.","كل رقم على الشاشة له مصدر مكتوب."],
 outputs=["data.csv","chart.html + mp4"],
 kw=["chart","dataviz","data visualization","dashboard","d3","infographic","counter","statistics"]),
dict(n="08", slug="ui-motion-microinteractions", ar="موشن الواجهات والتفاعلات الدقيقة", en="UI Motion & Microinteractions",
 desc="حركة واجهات بمستوى الجوائز: أزرار وقوائم وانتقالات صفحات بفيزياء النوابض، وFramer Motion وGSAP وCSS، وتنسيق الظهور المتدرّج، واحترام prefers-reduced-motion.",
 trig_ar=["حركة الواجهة","انيميشن للموقع","تأثيرات تفاعلية","hover"], trig_en=["ui animation","microinteraction","framer motion","page transition","spring animation","scroll trigger"],
 pipeline=["حدّد وظيفة كل حركة: توجيه، أو تغذية راجعة، أو متعة؛ احذف ما لا وظيفة له.","نوابض بدل المنحنيات الزمنية: stiffness 300 وdamping 30 وmass 1 كبداية.","تنسيق الظهور: الأهم أولاً، وإجمالي التدرّج أقل من 500ms.","أداء: transform وopacity فقط، وwill-change عند الحاجة، ولا تحريك layout.","إتاحة: بديل ثابت عند prefers-reduced-motion، ولا وميض أكثر من 3 مرات في الثانية."],
 gates=["لا حركة أطول من 700ms في الواجهات.","60 إطاراً في الثانية على جهاز متوسط.","كل حركة لها بديل لمن يطلب تقليل الحركة."],
 outputs=["مكوّنات React/HTML مع الحركة","motion-tokens.json"],
 kw=["framer motion","gsap","ui motion","microinteraction","transition","hover","scroll","css animation","spring"]),
dict(n="09", slug="image-prompt-forge", ar="مصنع برومبتات الصور", en="Image Prompt Forge",
 desc="برومبت صورة احترافي من مواصفة واحدة إلى كل منصة: Midjourney (المعاملات)، وFlux (لغة طبيعية)، وSDXL (أوزان وسلبي)، وDALL·E/ChatGPT (قيود أولاً)، وIdeogram (نص مقتبس)، وNanoBanana، مع فحص بالأداة وقفل الشخصية والأسلوب والمكان.",
 trig_ar=["برومبت صورة","اكتب برومبت","ميدجورني","صورة بالذكاء الاصطناعي","برومبت احترافي"], trig_en=["image prompt","midjourney prompt","flux prompt","stable diffusion prompt","dalle prompt","ideogram"],
 pipeline=["المواصفة: الموضوع، والفعل، والبيئة، والوقت، واللقطة، والزاوية، والعدسة، والإضاءة، واللوحة، والأسلوب، والنسبة، والسلبيات.","الأقفال: Character Lock وStyle Lock وLocation Lock تُنسخ حرفياً في كل برومبت للاتساق.","الصياغة لكل منصة: Midjourney بالمعاملات (--ar --s --c)، وSDXL بالأوزان والسلبي، وFlux وDALL·E بجمل طبيعية تبدأ بالقيود.","الفحص: scripts/image_prompt_forge.py يبني الصيغ ويفحص الاكتمال والتناقض (إضاءتان، عدستان) والسلبيات الناقصة.","تسليم 3 صيغ: الأساسية، ونسخة بالتباين الأعلى، ونسخة بزاوية مختلفة، مع تعليمات التكرار."],
 gates=["لا أسماء فنانين أحياء ولا أشخاص حقيقيين.","اتجاه ضوء واحد وعدسة واحدة.","النص المرئي بالعربية يُوضع بين علامتي اقتباس وتُذكر المنصة الداعمة."],
 outputs=["spec.json","prompts.md لكل منصة","lint.json"],
 kw=["image prompt","midjourney","stable diffusion","flux","dall","prompt","image generation","comfyui","sdxl","ideogram"], scripts=True),
dict(n="10", slug="video-prompt-director", ar="مخرج برومبتات الفيديو", en="Video Prompt Director",
 desc="برومبتات فيديو لمنصات Veo وSora وKling وRunway وLuma وPika وHailuo: لقطة بلقطة مع حركة الكاميرا وسرعتها والعدسة والإضاءة وحركة البيئة والمدة ومعدل الإطارات، وإطار مفتاحي أول لثبات الهوية، وخطة تكرار اللقطات الفاشلة.",
 trig_ar=["برومبت فيديو","سورا","فيو","كلينغ","فيديو بالذكاء الاصطناعي"], trig_en=["video prompt","sora prompt","veo prompt","kling","runway gen","luma","image to video"],
 pipeline=["الإطار: المنصة والمدة لكل لقطة (5 إلى 10 ثوانٍ) والنسبة والأسلوب.","الأقفال من image-prompt-forge تُعاد حرفياً في كل لقطة.","صيغة اللقطة: [الأقفال] + [الفعل عبر الزمن] + [حركة الكاميرا وسرعتها] + [العدسة] + [الإضاءة] + [حركة البيئة] + [المدة وfps] + [الأسلوب] + [النسبة].","إطار مفتاحي أول لكل لقطة (image-to-video) عند توفره.","QA بعد التوليد: انجراف الهوية، والأيدي، والفيزياء، والنص، والاستمرارية؛ أعد اللقطة الفاشلة فقط."],
 gates=["حركة كاميرا واحدة لكل لقطة.","لا تزييف لأشخاص حقيقيين.","المدة ضمن حدود المنصة."],
 outputs=["shotlist.md","prompts/ لكل منصة","qa-checklist.md"],
 kw=["video prompt","sora","veo","runway","kling","text to video","image to video","camera movement","cinematic"], scripts=True),
dict(n="11", slug="cinema-director-7layers", ar="المخرج السينمائي (7 طبقات)", en="Cinema Director",
 desc="تصميم مشاهد بصرية بسبع طبقات: الهوية، والعالم، والفعل والفيزياء، والكاميرا والعدسة، والإضاءة، والمواد والجو، واللون والقصة، مع أوراق مرجعية 360° للشخصيات والأماكن واستمرارية بين اللقطات.",
 trig_ar=["اخراج","مشهد سينمائي","ورقة شخصية","استمرارية","شوت ليست"], trig_en=["cinematic scene","character sheet","shot continuity","film look","director"],
 pipeline=["الطبقات السبع لكل مشهد مكتوبة قبل أي برومبت.","ورقة شخصية 360° (أمام، جانب، خلف، تعبيرات) وورقة مكان بأربع زوايا.","خطة الإضاءة بنِسَب ونوع المصدر وكلفن.","قائمة اللقطات بالعدسة والحركة والانتقال.","تحويل إلى برومبتات عبر image-prompt-forge وvideo-prompt-director."],
 gates=["اتجاه ضوء ثابت داخل المشهد.","الملابس والدعائم ثابتة بين اللقطات.","لا تناقض بين العدسة والمسافة المعلنة."],
 outputs=["scene-spec.json","reference-sheets.md","shotlist.md"],
 kw=["cinematic","film","director","shot list","storyboard","lighting","camera","lens","continuity"]),
dict(n="12", slug="storyboard-shotlist", ar="الستوري بورد وقائمة اللقطات", en="Storyboard & Shot List",
 desc="يحوّل أي فكرة أو سكربت إلى بنية إيقاعية (خطّاف، تمهيد، تصعيد، ذروة، نداء) ثم قائمة لقطات مرقّمة بالأزمنة ونوع اللقطة والحركة والصوت والنص على الشاشة، ولوحات مصغّرة SVG لكل لقطة.",
 trig_ar=["ستوري بورد","قائمة لقطات","تقسيم المشاهد","بيت شيت"], trig_en=["storyboard","shot list","beat sheet","scene breakdown"],
 pipeline=["الإيقاعات الخمسة بأزمنة تراكمية تساوي المدة الكلية.","لكل إيقاع لقطة أو لقطتان؛ لا أكثر من لقطة كل 2.5 ثانية في الريلز.","الجدول: # · الوقت · نوع اللقطة · العدسة · الحركة · الفعل · الإضاءة · الصوت · النص · الانتقال.","لوحات مصغّرة SVG بسيطة (مستطيلات ودوائر) لتوضيح التكوين.","مراجعة: هل يُفهم الفيديو بلا صوت؟"],
 gates=["الخطّاف في أول 1.5 ثانية.","نداء واحد في الختام.","كل لقطة تضيف معلومة جديدة."],
 outputs=["storyboard.md","thumbs.svg"],
 kw=["storyboard","shot list","beat sheet","script","scene","video content","reel"]),
dict(n="13", slug="brand-identity-logo", ar="الهوية البصرية والشعار", en="Brand Identity & Logo",
 desc="هوية كاملة من الصفر: شعار SVG متجه بثلاث نسخ (أساسي، أيقونة، أحادي)، ولوحة ألوان بأدوار وتباينات مفحوصة، وخطوط عربية ولاتينية متناغمة، ونبرة صوت، وقوالب سوشيال، ودليل استخدام من صفحة واحدة.",
 trig_ar=["شعار","لوجو","هوية بصرية","براند","دليل الهوية"], trig_en=["logo","brand identity","brand guidelines","color palette","brand kit"],
 pipeline=["الاستبيان: القيم الثلاث، والجمهور، والمنافسون، وما يجب ألا تشبهه.","3 اتجاهات شعار مختلفة جذرياً كـ SVG، ثم اختيار واحد وتنقيحه.","لوحة ألوان بأدوار (أساسي، ثانوي، تمييز، خلفية، نص) بتباين WCAG AA مفحوص بالكود.","الخطوط: عربي ولاتيني بنفس المزاج، ومقاسات واضحة.","قوالب: غلاف، ومنشور مربّع، وستوري، وبطاقة؛ وملف brand.md."],
 gates=["الشعار يُقرأ بحجم 24px.","لا تدرّجات في النسخة الأحادية.","كل لون له تباين مقاس مع خلفيته."],
 outputs=["logo.svg ×3","brand.md","tokens.json","templates/"],
 kw=["brand","logo","identity","design tokens","color palette","favicon","typography","style guide"]),
dict(n="14", slug="svg-illustration-icons", ar="الرسوم المتجهة والأيقونات", en="SVG Illustration & Icons",
 desc="رسوم SVG نظيفة من الكود: أيقونات متناسقة بشبكة 24px، ورسوم مسطّحة للمواقع والعروض، وشخصيات بسيطة، وأنماط خلفية، وتحويلها إلى PNG بأحجام متعددة وإلى favicon كامل.",
 trig_ar=["ايقونة","أيقونات","رسم svg","رسمة","فافيكون"], trig_en=["svg icon","icon set","vector illustration","favicon","flat illustration"],
 pipeline=["شبكة وسُمك خط موحّدان (24px، 2px) ونهايات مستديرة.","رسم بالبدائيات مع تعليق لكل جزء، وبذرة ثابتة لأي عشوائية.","اختبار بأحجام 16 و24 و48 و192؛ ما لا يُقرأ عند 16 يُبسّط.","تصدير PNG بـ PIL أو المتصفح، وfavicon.ico وmanifest.","تحسين SVG (إزالة المعرّفات غير المستخدمة والدقة الزائدة)."],
 gates=["viewBox مربّع للأيقونات.","لا نص داخل الأيقونة.","ملف الأيقونة أقل من 4KB."],
 outputs=["icons/*.svg","sprite.svg","favicon set + manifest"],
 kw=["svg","icon","favicon","illustration","vector","imagemagick","sprite","diagram"]),
dict(n="15", slug="diagrams-mermaid-architecture", ar="المخططات والرسوم الهندسية", en="Diagrams & Architecture Drawings",
 desc="مخططات Mermaid وSVG لتدفقات العمل والمعماريات وقواعد البيانات والتسلسلات والخرائط الذهنية، بقواعد وضوح: اتجاه واحد، وتسميات فعلية، وألوان بأدوار، وتصدير PNG/SVG.",
 trig_ar=["مخطط","دياجرام","رسم توضيحي","خريطة ذهنية","مخطط معماري"], trig_en=["diagram","mermaid","flowchart","sequence diagram","architecture diagram","mindmap","erd"],
 pipeline=["اختر النوع من السؤال: تدفق = flowchart، زمن = sequence، بيانات = ER، قرارات = decision tree.","اكتب Mermaid بتسميات أفعال على الأسهم، واتجاه واحد (TB أو LR).","لا أكثر من 12 عقدة في المخطط الواحد؛ قسّم ما زاد.","ألوان بأدوار (مصدر، معالجة، تخزين، خارجي) بتباين مقاس.","صدّر عبر mmdc إن وُجد، أو ارسم SVG مباشر للمخططات التي لا يدعمها Mermaid."],
 gates=["كل سهم له تسمية.","لا تقاطعات غير ضرورية.","يُقرأ بالأبيض والأسود."],
 outputs=["diagram.mmd","diagram.svg/png"],
 kw=["mermaid","diagram","flowchart","architecture","erd","sequence","excalidraw","plantuml","graphviz"]),
dict(n="16", slug="pixel-art-game-assets", ar="بكسل آرت وأصول الألعاب", en="Pixel Art & Game Assets",
 desc="سبرايتات بكسل آرت وورق حركة (مشي، قفز، هجوم) بأربع أو ثماني جهات، وبلاطات أرضية، وواجهات، ومؤثرات، بلوحة ألوان مقفلة ومولّد إجرائي بـ Python، ومخرجات لمحركات RPG Maker وGodot وPICO-8.",
 trig_ar=["بكسل ارت","سبرايت","لعبة بكسل","شخصية لعبة"], trig_en=["pixel art","sprite sheet","tileset","game asset","8-bit","walk cycle sprite"],
 pipeline=["الموجز: الموضوع والحجم (16/32/48) واللوحة والمحرك وجهات الحركة.","مولّد إجرائي: دالة draw(direction, pose) ببارامترات الأطراف، فتبقى كل الإطارات على النموذج.","لوحة مقفلة بمواد (تمييز، أساس، ظل، خط) والظل من أعلى اليسار.","تصدير ورقة بترتيب المحرك وGIF معاينة ومعاينة مكبّرة ×4.","مراجعة: التلامس والمرور، وثبات الحجوم، والإطارات المحتجزة عند الضربة."],
 gates=["لا ألوان خارج اللوحة.","حدود 1px متصلة.","الحجوم ثابتة بين الإطارات."],
 outputs=["spec.json","sheet.png","preview.gif"],
 kw=["pixel art","sprite","tileset","game","godot","unity","rpg maker","aseprite","phaser"]),
dict(n="17", slug="thumbnail-social-graphics", ar="الصور المصغّرة وتصاميم السوشيال", en="Thumbnails & Social Graphics",
 desc="صور مصغّرة ليوتيوب ومنشورات وستوريات وأغلفة بقواعد الجذب: وجه أو عنصر واحد كبير، وثلاث كلمات كحد أقصى، وتباين عالٍ، وتصميم بـ HTML/CSS يُصوَّر بدقة عالية، مع نسخ A/B.",
 trig_ar=["ثمبنيل","صورة مصغرة","غلاف","منشور","ستوري","بوست"], trig_en=["thumbnail","social post","story design","cover image","og image"],
 pipeline=["الرسالة في 3 كلمات والعاطفة المستهدفة.","التكوين: عنصر بطل يملأ 40% من الإطار، ونص في منطقة آمنة، وسهم أو دائرة توجيه عند الحاجة.","HTML/CSS بأبعاد المنصة (1280×720، 1080×1080، 1080×1920) وتصويرها بـ Playwright.","نسختان A/B تختلفان في عنصر واحد فقط.","فحص القراءة بتصغير 10%."],
 gates=["النص يُقرأ عند عرض 160px.","لا أكثر من 3 ألوان رئيسية.","لا ادعاءات مضلّلة."],
 outputs=["thumb-a.png / thumb-b.png","template.html"],
 kw=["thumbnail","social media","youtube","instagram","og image","cover","poster","graphic"]),
dict(n="18", slug="photo-lighting-plan", ar="تخطيط الإضاءة للصور والفيديو", en="Lighting Plan",
 desc="خطة إضاءة لأي تصوير أو مشهد مولّد: الهدف العاطفي، ونسبة المفتاح إلى التعبئة، ونوع المصادر وأحجامها ومواضعها، وكلفن، والجِل، وإعدادات التعريض، ومخطط SVG من الأعلى، وتشخيص الإضاءة السيئة في صورة موجودة.",
 trig_ar=["اضاءة","خطة اضاءة","تصوير بورتريه","اضاءة منتج"], trig_en=["lighting plan","three point lighting","key light","exposure","relight"],
 pipeline=["الهدف: المزاج والنوع (بورتريه، منتج، داخلي، سينمائي).","المفتاح: الاتجاه والارتفاع والحجم والمسافة؛ ثم التعبئة بنسبة معلنة (2:1 ناعم، 8:1 درامي).","الحافة والخلفية والعملي؛ كلفن لكل مصدر وتوافقها.","حساب التعريض بالقانون التربيعي العكسي عند تغيير المسافات.","مخطط من الأعلى SVG وقائمة معدات أو كلمات الإضاءة للبرومبت."],
 gates=["اتجاه واحد للمفتاح.","لا خلط كلفن غير مقصود.","الظلال مقروءة لا سوداء صماء."],
 outputs=["lighting-plan.md","diagram.svg","prompt-lighting-vocabulary.txt"],
 kw=["lighting","exposure","photography","cinematography","key light","gel","portrait","product photo"]),
dict(n="19", slug="image-critique-reverse-prompt", ar="نقد الصور واستخراج البرومبت", en="Image Critique & Reverse Prompt",
 desc="تحليل أي صورة: التكوين، والإضاءة، واللون، والحدة، وعيوب الذكاء الاصطناعي (أيدٍ، نص، تماثل)، وقراءة النص OCR، ودرجة من 100 بمعايير، ثم إعادة هندسة برومبت يعيد إنتاج الصورة أو يحسّنها.",
 trig_ar=["حلل الصورة","قيم الصورة","ما مشكلة الصورة","استخرج البرومبت"], trig_en=["critique image","analyze image","reverse prompt","what is wrong with this image","image score"],
 pipeline=["قياسات بالكود عند توفر الصورة: الهيستوغرام، والحدة، ونسبة التعريض، واللون المسيطر.","التكوين: الثلث، والخطوط الإرشادية، والفراغ، والاتزان.","عيوب التوليد: الأطراف، والنص، والانعكاسات، والتكرار.","الدرجة بمعايير معلنة (كل معيار من 20).","البرومبت العكسي بالطبقات السبع مع الفروق المقترحة للتحسين."],
 gates=["كل حكم له دليل بصري قابل للتحديد.","لا تخمين للهوية أو العِرق.","الدرجة تتبع المعايير لا الذوق."],
 outputs=["critique.md","score.json","reverse-prompt.md"],
 kw=["image analysis","vision","critique","ocr","reverse prompt","photo review","aesthetic"]),
dict(n="20", slug="ai-art-style-library", ar="مكتبة الأساليب الفنية للتوليد", en="AI Art Style Library",
 desc="قاموس أساليب لتوليد الصور والفيديو: سينمائي واقعي، وأنمي، وكلاي، وأكواريل، وخط حبر، وإيزومتريك، وسايبر، وفيلم 35mm قديم، ورسم أطفال؛ لكل أسلوب كلمات المفتاح والإضاءة والعدسة والسلبيات وما يجب تجنّبه قانونياً.",
 trig_ar=["ستايل صورة","اسلوب فني","انمي","واقعي سينمائي","اكواريل"], trig_en=["art style","anime style","claymation","watercolor prompt","isometric","film look"],
 pipeline=["حدّد المشاعر والجمهور ثم اختر أسلوباً من المكتبة.","استخرج كتلة الأسلوب (Style Lock) بكلماتها الدقيقة.","طابق الإضاءة والعدسة مع الأسلوب (الأنمي لا يحتاج f/1.4).","اذهب إلى image-prompt-forge بالقفل.","اختبر على موضوعين مختلفين لضمان أن الأسلوب ثابت."],
 gates=["لا أسماء استوديوهات أو فنانين كمعاملات؛ وصف الخصائص بدلها.","الأسلوب متناسق عبر سلسلة الصور.","السلبيات محددة لكل أسلوب."],
 outputs=["style-lock.txt","style-sheet.md"],
 kw=["style","aesthetic","anime","watercolor","art","prompt library","midjourney","lora"]),
dict(n="21", slug="product-photo-mockups", ar="صور المنتجات والموك-أب", en="Product Photos & Mockups",
 desc="صور منتجات للمتاجر والإعلانات: برومبتات استوديو بخلفية نظيفة أو مشهد حياة، وإضاءة منتج (softbox، gradient)، وزوايا قياسية، وموك-أب HTML/CSS للأجهزة والتغليف، وقواعد أمازون/نون للصور.",
 trig_ar=["صورة منتج","موك اب","تصوير منتج","صور للمتجر"], trig_en=["product photo","mockup","packshot","ecommerce image","device mockup"],
 pipeline=["نوع الصورة: رئيسية بخلفية بيضاء، أو نمط حياة، أو تفاصيل، أو مقارنة حجم.","الإضاءة من photo-lighting-plan: مفتاح كبير ناعم وتعبئة وحافة للزجاج والمعادن.","البرومبت عبر image-prompt-forge بقفل المنتج (الشكل واللون والشعار بلا تحريف).","موك-أب HTML: الصورة داخل جهاز أو عبوة بظلال CSS، وتصوير بدقة 2×.","فحص متطلبات المنصة: المنتج 85% من الإطار، ولا نص على الرئيسية."],
 gates=["الشعار الحقيقي لا يُولَّد بل يُركّب.","ظل واحد متناسق مع الضوء.","ألوان المنتج دقيقة."],
 outputs=["prompts.md","mockup.html + png"],
 kw=["product","mockup","ecommerce","packshot","photo","amazon","shopify","catalog"]),
dict(n="22", slug="comics-picture-books", ar="القصص المصوّرة وكتب الأطفال", en="Comics & Picture Books",
 desc="قصص مصوّرة وكتب أطفال من السكربت إلى الصفحات: تقسيم الصفحات واللوحات، وسكربت كومكس بالحوار والصوت، وأوراق شخصيات ثابتة الهوية، وبرومبتات لكل لوحة بالأقفال، وتخطيط الصفحة بـ HTML للطباعة.",
 trig_ar=["قصة مصورة","كومكس","كتاب اطفال","مانجا"], trig_en=["comic script","picture book","graphic novel","manga page","panel layout"],
 pipeline=["القصة: مشكلة، وثلاث محاولات، وحل، ودرس ضمني (للأطفال: 12 إلى 32 صفحة).","تقسيم الصفحات: نقطة تشويق في نهاية كل صفحة يمنى.","أوراق الشخصيات بالأقفال ونفس الملابس في كل لوحة.","برومبت لكل لوحة بالطبقات السبع، وفقاعات الحوار تُضاف بالكود لا بالتوليد.","تخطيط HTML للطباعة بـ CSS print وهوامش آمنة."],
 gates=["النص بالعربية الفصحى المبسّطة أو لهجة واضحة بحسب الجمهور.","لا أكثر من 25 كلمة في صفحة للأطفال.","الهوية ثابتة عبر كل اللوحات."],
 outputs=["script.md","character-sheets.md","panels-prompts.md","book.html"],
 kw=["comic","picture book","children","story","manga","panel","illustration","narrative"]),
dict(n="23", slug="ad-creative-30s", ar="الإعلان الإبداعي 30 ثانية", en="30-Second Ad Creative",
 desc="إعلان كامل لمنتج أو خدمة: 3 خطّافات بديلة، وبنية مشكلة-حل-إثبات-نداء، وسكربت تعليق صوتي بالعامية أو الفصحى، وقائمة لقطات، وبرومبتات توليد، ونسخة أنيميشن قابلة للتنفيذ بكلاود.",
 trig_ar=["اعلان","اعلان 30 ثانية","سبوت","اعلان منتج"], trig_en=["ad spot","30 second ad","commercial script","product ad","ugc ad"],
 pipeline=["الوعد الواحد: فائدة واحدة قابلة للإثبات.","3 خطّافات (سؤال، صدمة بصرية، نتيجة) لأول 2 ثانية.","البنية: 0-3 خطّاف، 3-10 مشكلة، 10-22 حل وإثبات، 22-30 نداء.","سكربت صوتي 70 كلمة كحد أقصى بإيقاع واضح.","قائمة لقطات وبرومبتات، أو تنفيذ أنيميشن عبر claude-animation-studio."],
 gates=["لا ادعاءات بلا إثبات.","نداء واحد.","النص على الشاشة يطابق المنطوق أو يختصره."],
 outputs=["ad-script.md","shotlist.md","hooks.md"],
 kw=["ad","advertising","commercial","marketing video","ugc","hook","copywriting","campaign"]),
dict(n="24", slug="reels-shorts-factory", ar="مصنع الريلز والشورتس", en="Reels & Shorts Factory",
 desc="محتوى عمودي قصير بكميات: أفكار من ركيزة المحتوى، وخطّاف في الثانية الأولى، وسكربت 45 ثانية، وترجمة مرئية كبيرة، وتصميم غلاف، وجدول نشر، وقالب أنيميشن عمودي جاهز.",
 trig_ar=["ريلز","شورتس","تيك توك","فيديو قصير","محتوى يومي"], trig_en=["reels","shorts","tiktok","short form","vertical video"],
 pipeline=["ركائز المحتوى الثلاث والجمهور.","10 أفكار بصيغة خطّاف + وعد + تحويل.","سكربت: خطّاف 1 ثانية، قيمة في 3 نقاط، نداء ناعم.","ترجمة مرئية: كلمة مفتاحية مميزة، وسطر أو سطران، 42 حرفاً كحد أقصى.","قالب عمودي 1080×1920 عبر claude-animation-studio، وغلاف من thumbnail-social-graphics."],
 gates=["أول ثانية فيها حركة ونص.","لا أكثر من 150 كلمة في 45 ثانية.","منطقة آمنة لواجهة المنصة."],
 outputs=["ideas.md","script.md","captions.srt","template.html"],
 kw=["reels","shorts","tiktok","social video","vertical","captions","hook","content calendar"], neg=("git","commit","codex-hook","webhook","x-hook")),
dict(n="25", slug="video-editing-captions", ar="خطة المونتاج والترجمة", en="Edit Plan & Captions",
 desc="خطة مونتاج احترافية لأي فيديو: القطع على الإيقاع، والانتقالات بمعنى، وتدرّج الألوان، والصوت على −14 LUFS، وملفات ترجمة SRT/VTT بقواعد القراءة، وأوامر ffmpeg جاهزة للقص والدمج والحرق.",
 trig_ar=["مونتاج","ترجمة فيديو","سبتايتل","قص فيديو","ffmpeg"], trig_en=["edit plan","captions","subtitles","srt","ffmpeg","color grade","cut on beat"],
 pipeline=["الترتيب والقطع: نقطة قطع كل إيقاع أو كل جملة؛ احسب الإيقاع من BPM.","الانتقالات: قطع صلب للتغيير، وتلاشٍ للاستمرار؛ لا أكثر من نوعين.","الصوت: مستوى −14 LUFS للمنصات، وقمة −1 dBTP، وموسيقى تحت الكلام بـ −18 dB.","الترجمة: 42 حرفاً في السطر، وسطران، ومن 1 إلى 7 ثوانٍ، وتزامن على بداية الكلمة.","أوامر ffmpeg للقص والدمج والحرق وتغيير النسبة مع التحقق من المخرجات."],
 gates=["لا ترجمة تغطي وجهاً أو نصاً مهماً.","مستوى الصوت مقاس لا مقدّر.","الترميز H.264 yuv420p للنشر."],
 outputs=["edit-plan.md","captions.srt","ffmpeg-commands.sh"],
 kw=["video editing","captions","subtitles","ffmpeg","transcode","color grade","audio level","srt"]),
]
