# -*- coding: utf-8 -*-
"""100 مهارة خارقة — تعريفات المهارات 51–75 (تصميم المواقع والبرمجة)."""
C = [
dict(n="51", slug="landing-page-premium", ar="صفحة الهبوط الفاخرة", en="Premium Landing Page",
 desc="صفحة هبوط من ملف HTML واحد بمستوى الجوائز: استبيان إجباري من 4 أسئلة (المنتج والوعد، والجمهور، والهوية، والنبرة)، ثم نسخة إقناعية، وتصميم بحركة GSAP وعمق بارالاكس، وتوافق جوال وRTL، وSEO وأداء، وتصوير للتحقق.",
 trig_ar=["صفحة هبوط","لاندنج","موقع لمنتج","صفحة بيع","صفحة تعريفية"], trig_en=["landing page","sales page","one-pager","product page","promo page"],
 pipeline=["الاستبيان: المنتج ووعده في جملتين، والجمهور (تقني، أعمال، مستهلك)، وألوان الهوية أو الافتراضي، والنبرة.","النسخة: عنوان 8-12 كلمة بالفائدة، وسطر فرعي، و3-6 ميزات بالنتيجة لا بالخاصية، ونداء واحد مكرر.","البنية: بطل، ومشكلة، وكيف يعمل، وإثبات اجتماعي، وأسعار إن وُجدت، وأسئلة شائعة، ونداء ختامي.","التصميم: HTML واحد بـ CSS وJS مضمّنين، وخطوط Google وGSAP من CDN فقط، ومتغيرات CSS للألوان، وحركة تحترم reduced-motion.","التحقق: تصوير بثلاثة أحجام، وفحص التباين وLighthouse، وSEO (العنوان والوصف وOG وJSON-LD)."],
 gates=["لا نص مكرر عام («حلول مبتكرة»).","يعمل على 375px بلا تمرير أفقي.","تباين AA وLCP أقل من 2.5 ثانية."],
 outputs=["index.html","copy.md","screenshots/"],
 kw=["landing page","gsap","marketing site","hero","conversion","html","tailwind","one page"]),
dict(n="52", slug="website-design-system", ar="تصميم المواقع ونظام التصميم", en="Website & Design System",
 desc="تصميم موقع كامل من الهوية إلى المكوّنات: رموز التصميم (ألوان، ومسافات، وخطوط عربية ولاتينية)، والوضع الداكن، والشبكة، والمكوّنات (أزرار، ونماذج، وبطاقات، وتنقّل)، وRTL أصلي، وصفحات نموذجية، ووثيقة نظام التصميم.",
 trig_ar=["صمم موقع","تصميم ويب","نظام تصميم","واجهة الموقع","قالب موقع"], trig_en=["design a website","design system","ui kit","design tokens","dark mode","rtl website"],
 pipeline=["الهدف والجمهور وخريطة الصفحات ورحلة المستخدم الأساسية.","الرموز: لوحة بأدوار مع نسخة داكنة، ومقياس مسافات 4px، ومقياس خطوط، وأنصاف أقطار، وظلال.","المكوّنات بحالاتها (عادي، تحويم، تركيز، معطّل، خطأ) وبـ RTL أصلي عبر الخصائص المنطقية.","الصفحات: الرئيسية، وصفحة محتوى، ونموذج، وصفحة خطأ؛ كل واحدة بثلاثة أحجام.","الوثيقة: tokens.json + components.md + أمثلة حية."],
 gates=["لا قيمة لون أو مسافة خارج الرموز.","كل مكوّن له حالة تركيز مرئية.","RTL بالخصائص المنطقية (margin-inline) لا بالنسخ."],
 outputs=["tokens.json","components.html/css","pages/","design-system.md"],
 kw=["design system","ui","web design","tailwind","css","components","figma","dark mode","responsive","rtl"]),
dict(n="53", slug="frontend-react-app", ar="تطبيق واجهة React", en="React Frontend App",
 desc="تطبيقات واجهة حديثة بـ React/Next.js أو Vue: بنية مجلدات واضحة، وإدارة حالة بسيطة، وجلب بيانات مع التحميل والخطأ، ونماذج مع تحقق، ومسارات، وTypeScript، واختبارات مكوّنات، وتحقق في متصفح حقيقي.",
 trig_ar=["react","next.js","تطبيق ويب","واجهة","vue","frontend"], trig_en=["react app","next.js","frontend","component","vue app","typescript ui"],
 pipeline=["المتطلبات كقصص مستخدم قصيرة مع معيار قبول لكل قصة.","البنية: features/ بكل ميزة مكوّناتها وخطافاتها، وui/ للمكوّنات العامة.","البيانات: طبقة API واحدة، وحالات تحميل/خطأ/فارغ لكل شاشة.","النماذج: تحقق بالمخطط (zod) ورسائل عربية واضحة.","التحقق: npm run build بلا أخطاء، واختبارات المكوّنات الأساسية، وتصوير في المتصفح."],
 gates=["لا any في TypeScript.","كل شاشة لها حالة خطأ وحالة فارغة.","البناء يمرّ والاختبارات تمرّ."],
 outputs=["مشروع كامل","README.md","screenshots/"],
 kw=["react","next.js","vue","frontend","typescript","component","tailwind","vite","state management"]),
dict(n="54", slug="backend-api-design", ar="تصميم الواجهات الخلفية وAPI", en="Backend & API Design",
 desc="واجهات API متينة (REST أو GraphQL): مواصفة OpenAPI أولاً، وتسمية موارد متسقة، وترقيم الصفحات، والأخطاء الموحّدة، والمصادقة، والحدود، والإصدارات، وتنفيذ بـ Node/Python/Workers مع اختبارات تكامل وتوثيق تلقائي.",
 trig_ar=["api","باك اند","خادم","rest","واجهة برمجية","endpoint"], trig_en=["api design","rest api","backend","openapi","graphql","endpoint","fastapi","express"],
 pipeline=["الموارد والعمليات من حالات الاستخدام، وOpenAPI 3.1 قبل الكود.","الاتفاقيات: أسماء جمع، وترقيم بالمؤشر، وتصفية موحّدة، وأخطاء بصيغة واحدة (code، message، details).","الأمان: مصادقة، وتفويض لكل مسار، وحدود معدل، وتحقق من المدخلات بالمخطط.","التنفيذ: طبقات (مسار، خدمة، مخزن) واختبارات تكامل لكل مسار بحالة نجاح وفشل.","التوثيق من المواصفة، وأمثلة curl، وسجل تغييرات الإصدار."],
 gates=["كل مسار في OpenAPI وله اختبار.","لا سر في الكود؛ متغيرات بيئة.","الأخطاء لا تكشف تفاصيل داخلية."],
 outputs=["openapi.yaml","src/","tests/","README.md"],
 kw=["api","rest","graphql","backend","openapi","fastapi","express","node","python","server"]),
dict(n="55", slug="database-schema-migrations", ar="مخطط قاعدة البيانات والترحيلات", en="Database Schema & Migrations",
 desc="تصميم قواعد بيانات صحيحة: الكيانات والعلاقات، والتطبيع 3NF مع تطبيع عكسي مبرّر، والأنواع الدقيقة (NUMERIC للمال، TIMESTAMPTZ)، والفهارس من أنماط الاستعلام، والقيود، وترحيلات قابلة للتراجع، ومخطط ERD.",
 trig_ar=["قاعدة بيانات","مخطط جداول","migration","erd","تصميم جداول"], trig_en=["database schema","migration","erd","normalize","postgres schema","prisma schema","data model"],
 pipeline=["الكيانات (الأسماء) والصفات والعلاقات من المتطلبات.","المفاتيح: BIGSERIAL أو UUID عند التعرّض في الروابط؛ المفاتيح الطبيعية عند الثبات الحقيقي.","التطبيع إلى 3NF، ثم تطبيع عكسي موثّق حيث يفرضه الأداء.","الأنواع والقيود: NUMERIC للمال، وTIMESTAMPTZ، وCHECK للحالات، وNOT NULL افتراضياً، وأعمدة created_at/updated_at.","الفهارس من الاستعلامات المتوقعة، والترحيل up/down، وERD بـ Mermaid."],
 gates=["لا FLOAT للمال.","كل مفتاح أجنبي له فهرس.","الترحيل يعمل up ثم down على قاعدة فارغة."],
 outputs=["schema.sql","migrations/","erd.mmd","schema.md"],
 kw=["database","schema","migration","postgres","mysql","sqlite","prisma","erd","normalization","index"]),
dict(n="56", slug="fullstack-saas-starter", ar="منصة SaaS كاملة", en="Full-Stack SaaS Starter",
 desc="تطبيق SaaS كامل من الصفر: مصادقة، ومستأجرون متعددون، ولوحة تحكم، وفوترة (وضع الاختبار)، وبريد، ولوجات، وتهيئة نشر على Cloudflare أو Vercel، مع قائمة الإطلاق والأمان.",
 trig_ar=["ساس","تطبيق متكامل","منصة","اشتراكات","نظام كامل"], trig_en=["saas","full stack app","multi-tenant","subscription app","starter kit","web app from scratch"],
 pipeline=["النطاق الأدنى القابل للإطلاق: 3 ميزات أساسية فقط.","البنية: واجهة (frontend-react-app) + API (backend-api-design) + قاعدة (database-schema-migrations).","المصادقة والمستأجرون: tenant_id في كل جدول وفي كل استعلام؛ اختبار عزل البيانات.","الفوترة في وضع الاختبار فقط مع مفاتيح اختبار؛ لا مفاتيح حية في المستودع.","النشر: متغيرات بيئة، ولوجات، وصفحة حالة، وقائمة إطلاق (نسخ احتياطي، حدود، سياسة خصوصية)."],
 gates=["اختبار عزل المستأجرين يمرّ.","لا مفتاح حي في الكود أو السجل.","قائمة الإطلاق مكتملة."],
 outputs=["monorepo/","DEPLOY.md","LAUNCH-CHECKLIST.md"],
 kw=["saas","full stack","auth","stripe","multi-tenant","next.js","supabase","deploy","starter"]),
dict(n="57", slug="mobile-app-builder", ar="تطبيقات الجوال", en="Mobile App Builder",
 desc="تطبيقات جوال بـ Flutter أو React Native/Expo: الشاشات من رحلة المستخدم، والتنقّل، والحالة، والتخزين المحلي، والإشعارات، ودعم العربية وRTL والخطوط، وبناء APK/IPA اختباري، وقائمة متطلبات المتاجر.",
 trig_ar=["تطبيق جوال","تطبيق اندرويد","ايفون","flutter","react native"], trig_en=["mobile app","flutter","react native","expo","android app","ios app"],
 pipeline=["الشاشات من رحلة المستخدم (لا أكثر من 7 في النسخة الأولى).","الإطار: Flutter للأداء والتصميم المخصص، أو Expo للسرعة ومشاركة كود الويب.","البنية: شاشات، ومكوّنات، وخدمات، وحالة مركزية بسيطة، وتخزين محلي.","العربية: RTL أصلي، وخط عربي، وتنسيق أرقام وتواريخ محلي.","البناء الاختباري والتشغيل على محاكي، وقائمة المتاجر (أيقونات، لقطات، سياسة خصوصية)."],
 gates=["يعمل في RTL بلا قلب خاطئ للأيقونات الاتجاهية.","لا تجميد في الواجهة أثناء الشبكة.","البناء ينجح على المنصتين."],
 outputs=["مشروع التطبيق","STORE-CHECKLIST.md"],
 kw=["mobile","flutter","react native","expo","android","ios","app","swift","kotlin"]),
dict(n="58", slug="cloudflare-edge-deploy", ar="النشر على Cloudflare والحافة", en="Cloudflare & Edge Deployment",
 desc="Workers وPages وD1 وKV وR2 وQueues: من wrangler.toml إلى النشر، مع الأسرار في متغيرات البيئة، والنطاقات، والتخزين المؤقت، والحدود، والسجلات، وبيئة معاينة قبل الإنتاج، وتجربة جافة قبل أي نشر.",
 trig_ar=["cloudflare","workers","pages","انشر الموقع","d1","wrangler"], trig_en=["cloudflare workers","cloudflare pages","wrangler","d1 database","edge function","deploy to cloudflare"],
 pipeline=["اختر الخدمة: Pages للمواقع الثابتة، وWorkers للـ API، وD1 للبيانات العلائقية، وKV للقراءة السريعة، وR2 للملفات.","wrangler.toml: البيئات (preview، production)، والروابط، والنطاقات؛ والأسرار بـ wrangler secret لا في الملف.","الكود: معالجة الأخطاء، وCORS محدود، والحدود، وcache-control صريح.","اختبار محلي بـ wrangler dev ثم نشر المعاينة ثم التحقق بطلب حقيقي.","الإنتاج بعد موافقة المستخدم فقط، وسجل النشر."],
 gates=["لا سر في wrangler.toml أو الكود.","المعاينة تُفحص قبل الإنتاج.","النشر إلى الإنتاج يحتاج موافقة صريحة."],
 outputs=["wrangler.toml","src/worker.ts","DEPLOY.md"],
 kw=["cloudflare","workers","pages","wrangler","d1","kv","r2","edge","serverless","deploy"]),
dict(n="59", slug="docker-ci-devops", ar="Docker وCI/CD", en="Docker & CI/CD",
 desc="حاوية ونشر مستمر لأي مشروع: Dockerfile متعدد المراحل صغير وآمن، وdocker-compose للتطوير، وGitHub Actions (فحص، اختبار، بناء، نشر) مع تخزين مؤقت وأسرار، وإصدارات دلالية، وتجارب جافة قبل أي دفع.",
 trig_ar=["docker","دوكر","ci","github actions","نشر تلقائي","pipeline"], trig_en=["dockerfile","docker compose","ci/cd","github actions","pipeline","containerize"],
 pipeline=["Dockerfile: صورة أساس صغيرة، ومراحل بناء/تشغيل، ومستخدم غير جذر، و.dockerignore.","compose للتطوير: الخدمات والشبكات والأحجام والمتغيرات من .env.example.","Actions: مصفوفة النسخ، وتخزين مؤقت للتبعيات، وفحص ثم اختبار ثم بناء ثم نشر على tag فقط.","الأسرار في GitHub Secrets، والصلاحيات الأدنى للـ token.","التحقق: docker build محلياً، وactionlint، وتشغيل جاف."],
 gates=["الصورة أقل من 300MB للخدمات العادية.","لا سر في الصورة أو السجل.","النشر على tag وموافقة بيئة."],
 outputs=["Dockerfile","docker-compose.yml",".github/workflows/ci.yml"],
 kw=["docker","compose","ci","cd","github actions","pipeline","kubernetes","helm","deploy","devops"]),
dict(n="60", slug="debugging-root-cause", ar="تصحيح الأخطاء من الجذر", en="Root-Cause Debugging",
 desc="إصلاح أي خطأ من جذره: إعادة الإنتاج أولاً، ثم العزل بالتنصيف، ثم الفرضية الواحدة والتجربة، ثم الإصلاح مع اختبار انحدار، ثم التحقق؛ لا يُقال «أُصلح» بلا تشغيل.",
 trig_ar=["خطأ","باج","لا يعمل","error","stack trace","صلح"], trig_en=["debug","bug","error","stack trace","not working","root cause","fix this"],
 pipeline=["أعد الإنتاج بأصغر خطوات؛ إن لم تُعد الإنتاج فلا تصلح بعد.","اقرأ الرسالة والتتبع كاملاً، وحدّد أول إطار في كودك.","انصّف: أي تغيير أو مدخل يُدخل الخطأ؟ git bisect أو تعليق نصف الكود.","فرضية واحدة قابلة للدحض وتجربة تدحضها أو تثبتها.","الإصلاح الأدنى + اختبار انحدار يفشل قبل الإصلاح ويمرّ بعده، ثم تشغيل كل الاختبارات."],
 gates=["الخطأ أُعيد إنتاجه قبل الإصلاح.","اختبار انحدار موجود.","لا إصلاح للأعراض فقط."],
 outputs=["root-cause.md","الإصلاح + الاختبار"],
 kw=["debug","bug","error","troubleshoot","root cause","stack trace","fix","logging","bisect"]),
dict(n="61", slug="code-review-refactor", ar="مراجعة الكود وإعادة الهيكلة", en="Code Review & Refactoring",
 desc="مراجعة صحة أولاً: الأخطاء، والحالات الحرجة، والانحدارات، والاختبارات الناقصة، ثم التبسيط وإزالة التكرار وتحسين الأسماء، بتعليقات قابلة للتنفيذ مرتبة بالخطورة، وإعادة هيكلة آمنة بخطوات صغيرة مع الاختبارات.",
 trig_ar=["راجع الكود","مراجعة","refactor","نظف الكود","حسن الكود"], trig_en=["code review","refactor","review this pr","clean code","simplify","technical debt"],
 pipeline=["افهم الهدف من التغيير قبل القراءة.","الصحة: مسارات الخطأ، والقيم الفارغة، والتزامن، والحدود، والأمان.","الاختبارات: ما الذي يُغيَّر ولا يغطيه اختبار؟","التبسيط: التكرار، والدوال الطويلة، والأسماء، والتعليقات الزائدة.","التقرير بالخطورة (حرج، مهم، تحسين) مع سيناريو فشل لكل ملاحظة؛ وإعادة الهيكلة بخطوات تمرّ فيها الاختبارات بعد كل خطوة."],
 gates=["كل ملاحظة لها سيناريو فشل ملموس.","لا إعادة هيكلة بلا اختبارات تحميها.","الملاحظات مرتبة بالخطورة."],
 outputs=["review.md","refactor-plan.md"],
 kw=["code review","refactor","clean code","simplify","pull request","quality","lint","technical debt"]),
dict(n="62", slug="testing-suite-complete", ar="منظومة الاختبارات الكاملة", en="Complete Testing Suite",
 desc="اختبارات تثبت أن الكود يعمل: وحدة، وتكامل، ونهاية إلى نهاية بـ Playwright، وخصائص، وبيانات اختبار واقعية بحالات حرجة (فارغ، حدود، يونيكود، عدائي)، وتغطية مقاسة، وكشف الاختبارات المتقلبة.",
 trig_ar=["اختبارات","تست","unit test","e2e","تغطية","pytest","jest"], trig_en=["write tests","unit tests","e2e tests","playwright test","test coverage","pytest","jest","vitest"],
 pipeline=["خريطة المخاطر: ما الذي يكسر المستخدم إن فشل؟ اختبره أولاً.","الوحدة: دالة واحدة، وحالة سعيدة وحالتان حرجتان على الأقل، وأسماء تصف السلوك.","التكامل: قاعدة حقيقية مؤقتة، وبيانات بذر، وتنظيف.","E2E: 3 إلى 5 رحلات مستخدم أساسية بـ Playwright مع محددات ثابتة.","بيانات الاختبار: مصانع ببذرة ثابتة وحالات حرجة؛ وتقرير التغطية والمتقلبات."],
 gates=["كل اختبار يفشل إن أُزيل السلوك.","لا اختبار يعتمد على ترتيب أو وقت.","الاختبارات تمرّ محلياً وفي CI."],
 outputs=["tests/","factories.py أو factories.ts","coverage-report.md"],
 kw=["test","testing","unit test","e2e","playwright","pytest","jest","coverage","fixture","mock"]),
dict(n="63", slug="security-audit-stride", ar="التدقيق الأمني STRIDE", en="Security Audit (STRIDE)",
 desc="مراجعة أمنية دفاعية: نمذجة تهديدات STRIDE، والأسرار المسرّبة، والحقن (SQL، أوامر، XSS)، والمصادقة والجلسات، والتبعيات الضعيفة، والتهيئة، وترويسات الأمان، بدرجات خطورة وأدلة وإصلاحات، للقراءة فقط.",
 trig_ar=["امان","ثغرات","تدقيق امني","security","اختراق","حماية الموقع"], trig_en=["security audit","threat model","vulnerability","owasp","secrets scan","security headers","stride"],
 pipeline=["حدود النظام وتدفقات البيانات ومخطط بسيط.","STRIDE لكل تدفق: انتحال، وتلاعب، وإنكار، وكشف، وحجب، ورفع صلاحية.","الفحص: الأسرار بالأنماط، والحقن في كل مدخل، والمصادقة والجلسات، والتبعيات (npm audit/pip-audit)، والترويسات.","الخطورة بـ CVSS تقريبي ودليل (ملف وسطر) وإصلاح محدد لكل نتيجة.","التقرير بالأولوية وخطة إصلاح؛ لا استغلال ولا تغيير في الكود."],
 gates=["كل نتيجة لها دليل وسطر.","لا استغلال فعلي للثغرات.","التقرير يميّز المؤكد عن المحتمل."],
 outputs=["threat-model.md","security-report.md","fix-plan.md"],
 kw=["security","stride","threat model","owasp","vulnerability","secrets","injection","audit","headers"]),
dict(n="64", slug="git-github-workflow", ar="سير عمل Git وGitHub", en="Git & GitHub Workflow",
 desc="إدارة المستودعات باحتراف: الفروع والرسائل الاصطلاحية، وطلبات الدمج بوصف واضح، وحل التعارضات، والإصدارات، وحماية الفروع، وCODEOWNERS، وإصلاح أخطاء Git الشائعة (rebase، reset، reflog) بأمان، ولا دفع أو نشر بلا موافقة.",
 trig_ar=["جيت","github","كومت","pull request","فرع","دمج","تعارض"], trig_en=["git","github","commit","pull request","merge conflict","rebase","release","branch"],
 pipeline=["الحالة أولاً: git status وlog وdiff قبل أي أمر.","الفرع لكل مهمة، ورسائل اصطلاحية (feat/fix/docs) بالسبب لا الوصف.","PR: العنوان، والسبب، وما تغيّر، وكيف اختُبر، ولقطات؛ ومراجعة ذاتية للـ diff.","التعارضات: افهم الطرفين، وادمج بالمعنى، وشغّل الاختبارات.","الإصدار: تاغ دلالي وسجل تغييرات؛ أي push أو release بعد موافقة صريحة."],
 gates=["لا force push على الفروع المشتركة.","لا دفع أو نشر بلا موافقة.","الاختبارات تمرّ قبل الـ PR."],
 outputs=["PR-description.md","CHANGELOG.md"],
 kw=["git","github","commit","pull request","branch","merge","rebase","release","changelog","worktree"]),
dict(n="65", slug="automation-scripts-cli", ar="سكربتات الأتمتة وأدوات سطر الأوامر", en="Automation Scripts & CLI Tools",
 desc="سكربتات Python/Bash/PowerShell وأدوات CLI صغيرة متينة: وسائط واضحة ومساعدة، ومعالجة أخطاء، وسجلات، وتجربة جافة، وتعامل آمن مع الملفات (لا حذف بلا تأكيد)، وتثبيت بسيط، واختبارات.",
 trig_ar=["سكربت","اتمتة","اداة سطر اوامر","bash","powershell","نظم الملفات"], trig_en=["script","cli tool","automate","bash script","powershell","batch rename","file organizer"],
 pipeline=["المدخل والمخرج والأثر الجانبي في سطر واحد قبل الكتابة.","واجهة: argparse أو click، ومساعدة بالأمثلة، وخيار --dry-run لأي تغيير.","المتانة: ترميز UTF-8 للعربية، ومسارات بمسافات، وأخطاء مفسّرة، وإنهاء برمز.","الأمان: لا حذف نهائي؛ نقل إلى مجلد trash أو تأكيد.","اختبار على مجلد مؤقت، وREADME بسطر التثبيت."],
 gates=["--dry-run موجود لكل أمر يغيّر.","يعمل مع أسماء عربية ومسافات.","لا حذف بلا تأكيد."],
 outputs=["tool.py أو tool.sh","README.md","tests/"],
 kw=["script","cli","automation","bash","powershell","python script","argparse","file","batch"]),
dict(n="66", slug="browser-automation-playwright", ar="أتمتة المتصفح بـ Playwright", en="Browser Automation (Playwright)",
 desc="تشغيل المتصفح برمجياً للاختبار والجمع والتصوير: محددات ثابتة، وانتظارات صحيحة، وتسجيل الدخول بجلسة محفوظة يوفّرها المستخدم، وتصوير صفحات كاملة وPDF، ومعالجة النوافذ، والتوقف عند CAPTCHA والدفع والإرسال.",
 trig_ar=["افتح الموقع","اضغط","عبئ النموذج","اتمتة المتصفح","playwright","صور الصفحة"], trig_en=["playwright","browser automation","fill form","screenshot page","click through","headless browser"],
 pipeline=["الهدف وخطوات المستخدم البشري أولاً، ثم ما يُؤتمت.","المحددات: getByRole وgetByLabel وdata-testid؛ لا XPath هش.","الانتظار على الحالة (expect visible) لا على الزمن.","الجلسة: storageState من المستخدم؛ لا إدخال كلمات مرور بالكود.","التوقف الإجباري قبل أي إرسال أو دفع أو CAPTCHA، وتسجيل فيديو/لقطات للتحقق."],
 gates=["لا تجاوز CAPTCHA ولا إدخال بيانات دخول.","لا إرسال نموذج بلا تأكيد.","كل خطوة لها لقطة أو تأكيد حالة."],
 outputs=["automation.py أو .spec.ts","screenshots/","run-log.md"],
 kw=["playwright","browser","automation","selenium","puppeteer","form","screenshot","headless","e2e"]),
dict(n="67", slug="performance-optimization", ar="تحسين الأداء", en="Performance Optimization",
 desc="تسريع المواقع والتطبيقات والاستعلامات بالقياس: Lighthouse وWeb Vitals، وتحليل الحزمة، والصور والخطوط، والتخزين المؤقت، وملفات تعريف الأداء للكود، وN+1 في قواعد البيانات، مع قبل/بعد بالأرقام.",
 trig_ar=["بطيء","تحسين الاداء","سرعة الموقع","lighthouse","تحميل بطيء"], trig_en=["performance","slow","optimize","lighthouse","web vitals","bundle size","profiling"],
 pipeline=["قِس أولاً: Lighthouse أو profiler أو EXPLAIN؛ سجّل الأرقام.","حدّد أكبر عنق زجاجة واحد (قاعدة 80/20).","الإصلاح الأقل مخاطرة أولاً: صور وخطوط وتخزين مؤقت قبل إعادة الهيكلة.","أعد القياس بنفس الطريقة؛ احتفظ بما حسّن فقط.","ميزانية أداء مكتوبة (LCP، حجم الحزمة، زمن الاستعلام) للمستقبل."],
 gates=["كل تحسين له قبل/بعد مقاس.","لا تحسين يكسر وظيفة.","الميزانية موثّقة."],
 outputs=["perf-report.md","budget.json"],
 kw=["performance","optimize","lighthouse","web vitals","bundle","cache","profil","speed","lazy load"]),
dict(n="68", slug="accessibility-wcag", ar="الإتاحة WCAG", en="Accessibility (WCAG 2.2)",
 desc="تدقيق وإصلاح الإتاحة: فحص آلي (axe) + تحقق يدوي (لوحة المفاتيح، وقارئ الشاشة، والتباين، والتكبير 200%، والحركة)، وRTL والعربية، والنماذج والأخطاء، بتقرير بمستوى A/AA وإصلاحات بالكود.",
 trig_ar=["اتاحة","ذوي الاحتياجات","wcag","قارئ الشاشة","تباين"], trig_en=["accessibility","a11y","wcag","screen reader","keyboard navigation","contrast"],
 pipeline=["الفحص الآلي على كل صفحة وتجميع النتائج.","لوحة المفاتيح: ترتيب التركيز، والظهور، وعدم الحصر، والاختصارات.","الدلالات: العناوين، والمعالم، والأسماء، والـ ARIA عند الحاجة فقط.","البصري: تباين 4.5:1، والتكبير، والحركة القابلة للإيقاف، والنص البديل ذو المعنى.","التقرير بالمعيار والخطورة والإصلاح، ثم إعادة الفحص بعد الإصلاح."],
 gates=["كل تفاعل يعمل بلوحة المفاتيح.","لا اعتماد على اللون وحده.","axe صفر أخطاء حرجة."],
 outputs=["a11y-report.md","fixes.diff"],
 kw=["accessibility","a11y","wcag","aria","screen reader","contrast","keyboard","axe","inclusive"]),
dict(n="69", slug="seo-content-architecture", ar="SEO وبنية المحتوى", en="SEO & Content Architecture",
 desc="ظهور في البحث بلا خدع: التدقيق التقني (الزحف، والفهرسة، والسرعة، والجوال)، والبنية (الصفحات الركيزة والعناقيد)، والكلمات بنية البحث، والعناوين والأوصاف، والبيانات المهيكلة JSON-LD المفحوصة، والمحتوى العربي المحسّن.",
 trig_ar=["سيو","seo","ظهور في جوجل","كلمات مفتاحية","بيانات مهيكلة"], trig_en=["seo","search ranking","keywords","json-ld","schema markup","site architecture","meta tags"],
 pipeline=["التدقيق التقني: robots وsitemap والفهرسة والسرعة والجوال والروابط المكسورة.","البنية: صفحة ركيزة لكل موضوع رئيسي و5-10 صفحات عنقود تربط بها.","الكلمات بنية البحث (معلومة، مقارنة، شراء) لا بالحجم فقط.","العناوين 50-60 حرفاً والأوصاف 150-160، وH1 واحد، وروابط داخلية بنص وصفي.","JSON-LD للنوع المناسب يصف ما تعرضه الصفحة فقط، مفحوص بالأداة."],
 gates=["لا بيانات مهيكلة لمحتوى غير ظاهر.","لا حشو كلمات.","كل صفحة لها قصد بحث واحد."],
 outputs=["seo-audit.md","content-map.md","jsonld.json"],
 kw=["seo","schema","json-ld","keywords","sitemap","meta","search","content strategy","backlinks"]),
dict(n="70", slug="technical-docs-readme", ar="التوثيق التقني وREADME", en="Technical Docs & README",
 desc="توثيق يُقرأ: README بنموذج (ماذا، لماذا، تثبيت في 3 أوامر، مثال، تهيئة، أسئلة)، وأدلة مستخدم، ومرجع API من الكود، وADRs للقرارات، وسجل تغييرات، وشروحات بالعربية بمصطلحات ثابتة.",
 trig_ar=["توثيق","readme","دليل الاستخدام","شرح الكود","وثّق"], trig_en=["readme","documentation","docs","api reference","user guide","adr","changelog"],
 pipeline=["القارئ أولاً: مبتدئ أم مطوّر أم مشغّل؟ وثيقة لكل قارئ.","README: جملة الهدف، ولقطة، وتثبيت بثلاثة أوامر مُجرَّبة، ومثال يعمل، والتهيئة، والأسئلة.","المرجع من الكود (docstrings) لا بالنسخ اليدوي.","ADR لكل قرار معماري: السياق، والخيارات، والقرار، والعواقب.","تجربة الوثيقة: شخص يتبعها من الصفر؛ أي خطوة فشلت تُصحَّح."],
 gates=["أوامر التثبيت مُجرَّبة فعلاً.","مصطلحات عربية ثابتة في مسرد.","لا توثيق يناقض الكود."],
 outputs=["README.md","docs/","adr/","CHANGELOG.md"],
 kw=["readme","documentation","docs","markdown","adr","changelog","api docs","technical writing"]),
dict(n="71", slug="python-pro", ar="بايثون المحترف", en="Python Pro",
 desc="كود Python إنتاجي: بنية حزمة، وtyping، وdataclasses/pydantic، ومعالجة أخطاء واضحة، وasync عند الحاجة، وpytest، وruff، وبيئة uv/venv، وتعبئة pyproject، وأداء بالقياس.",
 trig_ar=["بايثون","python","سكربت بايثون","مكتبة بايثون"], trig_en=["python","pytest","pydantic","asyncio","pyproject","python package","type hints"],
 pipeline=["البنية: src/package، وpyproject.toml، وبيئة معزولة.","الأنواع في كل توقيع، ونماذج بيانات بـ dataclass أو pydantic.","الأخطاء: استثناءات مخصصة، ولا except عارٍ، ورسائل بالسياق.","الاختبارات بـ pytest مع fixtures وparametrize؛ وruff للتنسيق والفحص.","القياس قبل التحسين، وREADME بأمثلة تعمل."],
 gates=["ruff وmypy بلا أخطاء.","تغطية الاختبارات للمنطق الأساسي.","لا print للتسجيل؛ logging."],
 outputs=["الحزمة","pyproject.toml","tests/"],
 kw=["python","pytest","pydantic","fastapi","asyncio","typing","ruff","uv","package"]),
dict(n="72", slug="typescript-node-pro", ar="TypeScript وNode المحترف", en="TypeScript & Node Pro",
 desc="كود TypeScript صارم لـ Node وBun وDeno: tsconfig صارم، وأنواع من المخطط (zod)، وأخطاء مميّزة، وESM، واختبارات vitest، وESLint، وبناء بـ tsup، وأداء وذاكرة بالقياس.",
 trig_ar=["typescript","node","جافاسكربت","npm","bun"], trig_en=["typescript","node.js","bun","deno","vitest","eslint","npm package"],
 pipeline=["tsconfig صارم (strict، noUncheckedIndexedAccess) وESM.","الأنواع من المصدر الواحد: مخطط zod يولّد النوع ويتحقق في الحدود.","الأخطاء: نتائج مميّزة أو استثناءات مخصصة؛ لا any ولا as غير مبرّر.","vitest للاختبار، وESLint، وtsup للبناء، وscripts واضحة في package.json.","القياس قبل التحسين، وREADME بأمثلة."],
 gates=["tsc بلا أخطاء وبلا any.","الاختبارات تمرّ.","لا تبعية بلا سبب."],
 outputs=["src/","package.json","tests/"],
 kw=["typescript","node","javascript","bun","deno","vitest","eslint","npm","esm"]),
dict(n="73", slug="legacy-code-migration", ar="تحديث الكود القديم والترحيل", en="Legacy Code Migration",
 desc="نقل الأنظمة القديمة بأمان: فهم السلوك الحالي باختبارات توصيف، وتقسيم الترحيل إلى شرائح (strangler)، وتحويل اللغات أو الأطر، وتوافق البيانات، وخطة تراجع، وقياس التكافؤ قبل القطع.",
 trig_ar=["كود قديم","ترحيل","حوّل الكود","تحديث النظام","من php الى"], trig_en=["legacy","migrate","convert code","framework migration","upgrade version","port to"],
 pipeline=["جرد النظام: الوحدات، والتبعيات، والمدخلات والمخرجات، وما لا يُفهم.","اختبارات توصيف تلتقط السلوك الحالي (حتى الأخطاء) قبل أي تغيير.","خطة شرائح: الأقل خطراً أولاً، وواجهة توافق بين القديم والجديد.","التحويل مع الاحتفاظ بالسلوك؛ أي تحسين يُؤجَّل لمرحلة لاحقة.","مقارنة المخرجات على بيانات حقيقية، وخطة تراجع، ثم القطع."],
 gates=["اختبارات التوصيف تمرّ على الجديد.","التراجع ممكن في كل شريحة.","لا تغيير سلوك غير موثّق."],
 outputs=["inventory.md","characterization-tests/","migration-plan.md"],
 kw=["legacy","migration","convert","port","upgrade","refactor","modernize","strangler"]),
dict(n="74", slug="software-architecture-adr", ar="هندسة البرمجيات والقرارات المعمارية", en="Software Architecture & ADRs",
 desc="تصميم أنظمة قبل البناء: الحدود والواجهات ونماذج البيانات، والتوسع وأنماط الفشل، والمفاضلات، وADRs، ومخططات، وخطة تنفيذ مرحلية بمعايير قتل، مبنية على الكود الفعلي لا الافتراضات.",
 trig_ar=["معمارية","تصميم النظام","architecture","بنية المشروع","قرار تقني"], trig_en=["architecture","system design","adr","boundaries","scalability","trade-off","design doc"],
 pipeline=["المتطلبات غير الوظيفية بالأرقام (المستخدمون، والزمن، والتوافر، والميزانية).","الحدود: السياقات والواجهات بينها وملكية البيانات.","الخيارات: 2-3 معماريات بالمفاضلات، والاختيار بالأدلة.","أنماط الفشل: ماذا يحدث عند سقوط كل مكوّن؟ وكيف نعرف؟","ADRs، ومخطط، وخطة مرحلية بمعيار نجاح وقتل لكل مرحلة."],
 gates=["كل قرار له ADR بالبدائل المرفوضة.","المتطلبات غير الوظيفية بأرقام.","الخطة لها معايير قتل."],
 outputs=["architecture.md","adr/","diagram.mmd","roadmap.md"],
 kw=["architecture","system design","adr","microservices","monolith","scalability","design patterns","ddd"]),
dict(n="75", slug="game-dev-web", ar="تطوير الألعاب للويب", en="Web Game Development",
 desc="ألعاب متصفح كاملة: حلقة لعب، وحالة، وإدخال، وفيزياء بسيطة، وأصول من pixel-art-game-assets، وصوت، وحفظ محلي، وجوال بلمس، بـ Canvas/Phaser/Three.js، وقابلة للنشر كملف HTML واحد.",
 trig_ar=["لعبة","اعمل لعبة","لعبة متصفح","phaser","game"], trig_en=["browser game","html5 game","phaser","canvas game","game loop","web game"],
 pipeline=["حلقة اللعب الأساسية في جملة (ما يفعله اللاعب كل 10 ثوانٍ) ومعيار الفوز والخسارة.","النموذج الأولي بأشكال بسيطة أولاً؛ الأصول لاحقاً.","الحلقة: update(dt) وrender منفصلتان، وحالة قابلة للحفظ.","الإدخال: لوحة ولمس، والصوت بـ WebAudio، والحفظ في localStorage.","الأصول من pixel-art-game-assets، والنشر كـ HTML واحد، واختبار على الجوال."],
 gates=["60 إطاراً على جوال متوسط.","يعمل باللمس ولوحة المفاتيح.","الحالة تُحفظ وتُستعاد."],
 outputs=["game.html","assets/","design.md"],
 kw=["game","phaser","canvas","godot","unity","game loop","physics","sprite","html5"]),
]
