# -*- coding: utf-8 -*-
"""100 مهارة خارقة — تعريفات المهارات 26–50 (البرومبتات والذكاء الاصطناعي وأدوات Office)."""
B = [
dict(n="26", slug="prompt-master-pro", ar="سيّد البرومبتات الاحترافي", en="Prompt Master Pro",
 desc="كتابة أي برومبت باحترافية ألف: يصطاد النقاط العمياء أولاً (المعلوم غير المذكور والمجهول غير المدرك)، ثم يبني البرومبت بصيغة الأقسام الثمانية (الدور، والسياق، والمهمة، والمدخلات، والقيود، وصيغة الإخراج، والحالات الحرجة، ومعيار الجودة)، ثم يفحصه بأداة linting بدرجة من 100، ثم يختبره على 3 حالات (عادية، حرجة، عدائية)، ويسلّم نسخة v1 مع نسختي A/B.",
 trig_ar=["برومبت","اكتب لي برومبت","حسن البرومبت","موجه","برومبت احترافي","prompt"], trig_en=["write a prompt","improve this prompt","prompt engineering","system prompt","refine prompt","better prompt"],
 pipeline=["المعايرة: من المستخدم بالنسبة للمهمة (خبير أم مبتدئ)، وما الموجود، ولماذا الآن.","اصطياد النقاط العمياء: قسّم المعرفة إلى 4 مربعات (معلوم مذكور، معلوم غير مذكور، مجهول مدرك، مجهول غير مدرك) واسأل عن الثاني والرابع فقط، بأسئلة تعرّف لا تذكّر (اختيارات ملموسة).","الاستخراج: أعد كتابة الطلب كهدف نهائي، واستنتج القيود الضمنية (الزمانية، والمكانية، والموارد، والجمهور).","البناء بالأقسام الثمانية مع تحديد الأسماء بدل الصفات (3 نقاط بـ15 كلمة بدل «قصير») وكل «لا تفعل» معها «افعل بدلها».","قفل الاتجاه الحر: اذكر صراحةً ما يقرره النموذج بنفسه وما يجب أن يبلّغ عنه.","الفحص: scripts/prompt_lint.py يعطي الدرجة والأقسام الناقصة والمخاطر (غموض، تناقض، سر، مدخلات غير مسوّرة).","الاختبار على 3 مدخلات مكتوبة مسبقاً مع المخرج المتوقع؛ لا يُقال «يعمل» بلا تشغيل.","التسليم: v1 في كتلة كود + سجل التغيير + نسختان A/B تختلفان في متغير واحد."],
 gates=["الدرجة 80+ من اللنتر قبل التسليم.","المدخلات غير الموثوقة مسوّرة بعلامات وتُوصف كبيانات لا أوامر.","اللغة محددة (عربي ← عربي).","لا طلب للكشف عن التفكير الداخلي؛ استنتاجات وأدلة فقط."],
 outputs=["blindspots.md","prompt-v1.md","lint.json","tests.md (3 حالات)","variants-ab.md"],
 kw=["prompt","prompt engineering","enrich prompt","refine prompt","meta prompt","instruction","few-shot","chain of thought","prompt template"], scripts=True),
dict(n="27", slug="system-prompt-architect", ar="مهندس برومبتات النظام", en="System Prompt Architect",
 desc="برومبتات نظام لمساعدين وGPTs مخصصة ومشاريع Claude: الشخصية والحدود والنبرة والأمثلة والرفض اللطيف وذاكرة السياق، مع ميزانية رموز لكل قسم وترتيب يراعي التخزين المؤقت وتأثير «المنتصف المفقود».",
 trig_ar=["برومبت نظام","تعليمات GPT","شخصية المساعد","system prompt","تعليمات المشروع"], trig_en=["system prompt","custom gpt instructions","assistant persona","project instructions","agent persona"],
 pipeline=["الهوية: الاسم، والدور، والجمهور، وما يرفضه وكيف.","الميزانية: حد أعلى من الرموز لكل قسم (هوية، قواعد، أمثلة، صيغة)، والمجموع يترك مكاناً للرد.","الترتيب: الثابت أولاً (للتخزين المؤقت)، والحاسم في البداية أو النهاية لا الوسط.","القواعد بصيغة إيجابية أولاً ثم الحدود، وكل حد له بديل.","مثال محادثة كامل واحد على الأقل بنفس الصيغة المطلوبة.","لنت بـ prompt-master-pro ثم اختبار 3 حالات منها محاولة تجاوز."],
 gates=["أقل من 8000 حرف لـ GPT المخصص.","لا أسرار ولا مفاتيح في البرومبت.","سلوك محدد عند الطلب خارج النطاق."],
 outputs=["system-prompt.md","token-budget.md","conversation-starters.md"],
 kw=["system prompt","persona","assistant","custom gpt","instructions","context window","guardrails"]),
dict(n="28", slug="agent-tool-instructions", ar="تعليمات الوكلاء والأدوات", en="Agent & Tool Instructions",
 desc="برومبتات الوكلاء وأوصاف الأدوات وملفات SKILL.md وCLAUDE.md: الهدف، والأدوات المسموحة، وشرط التوقف، والميزانية، ونقاط التوقف البشرية، والشرط اللاحق المُثبِت للإنجاز؛ ولكل أداة: ماذا تفعل ومتى ومتى لا وكل بارامتر بنوعه ومثاله وآثاره الجانبية.",
 trig_ar=["برومبت وكيل","وصف اداة","تعليمات agent","SKILL.md","CLAUDE.md","مهارة جديدة"], trig_en=["agent prompt","tool description","skill file","claude.md","agent instructions","mcp tool description"],
 pipeline=["حلقة الوكيل: الهدف، والأدوات، وشرط التوقف، والميزانية (أقصى خطوات ومحاولات)، ونقاط التوقف (دفع، حذف، إرسال، بيانات دخول).","الشرط اللاحق: ما الدليل القابل للرصد الذي يثبت «تم»؟","أوصاف الأدوات: متى تُستخدم ومتى لا، وكل بارامتر بالنوع والوحدة والمثال، والسلوك عند الفشل.","لـ SKILL.md: وصف يبدأ بـ Use when ويحوي المحفّزات بالعربية والإنجليزية، وخط إنتاج مرقّم، وبوابات جودة.","لنت بـ prompt-master-pro بنوع agent أو tool."],
 gates=["شرط توقف صريح وميزانية صريحة.","كل فعل خارجي له نقطة توقف بشرية.","نجاح الأداة لا يساوي نجاح المهمة: تحقق من الشرط اللاحق."],
 outputs=["AGENT.md أو SKILL.md","tools.json (أوصاف)","stop-conditions.md"],
 kw=["agent","tool","mcp","skill","claude.md","agents.md","subagent","orchestration","workflow"]),
dict(n="29", slug="structured-output-json", ar="المخرجات المهيكلة JSON", en="Structured Output & JSON",
 desc="إخراج قابل للتحليل برمجياً من أي نموذج: مخطط JSON Schema، واختيار آلية الإلزام (وضع JSON الأصلي، أو استدعاء أداة، أو نحو مقيّد، أو نص+محلّل)، ومسار تحليل-تحقق-إصلاح بمحاولات محدودة، وشكل الفشل والرفض و«لا أعرف».",
 trig_ar=["اخراج JSON","مخطط","schema","استخراج بيانات","output منظم"], trig_en=["json output","structured output","json schema","extraction prompt","function calling output","parse llm output"],
 pipeline=["المخطط أولاً مع أشكال الفشل: الرفض، وغير المعروف (null لا اختراع)، والخطأ.","الآلية: الأقوى المتاح (وضع المخطط الأصلي أو استدعاء أداة) قبل أي «رجاءً أعد JSON».","المحلّل: parse ثم validate (المخطط + قواعد العمل) ثم repair بإعادة الطلب مع الخطأ المحدد ثم fail-closed.","تسوير المدخلات غير الموثوقة داخل المخطط نفسه.","مجموعة انحدار من 10 حالات تشمل الفارغ والمكرر وغير المتوقع."],
 gates=["لا ثقة في الخام حتى من الوضع الأصلي.","المحاولات محدودة (3) ثم خطأ معرّف.","المفاتيح مطابقة تماماً للمخطط."],
 outputs=["schema.json","prompt.md","parser.py أو parser.ts","regression.jsonl"],
 kw=["json","schema","structured output","extraction","function calling","pydantic","zod","validation","parser"]),
dict(n="30", slug="llm-judge-evals", ar="قاضي النماذج ومجموعات التقييم", en="LLM Judge & Eval Suites",
 desc="تقييم أي ميزة ذكاء اصطناعي بأرقام: مواصفة المهمة، وطريقة التقييم (دقيق، قواعد، نموذج قاضٍ، بشري)، وقاضٍ بمعايير مسمّاة ومستويات مثبّتة لا «من 1 إلى 10»، ومعايرة على عينة بشرية، وفحص تحيزات الموضع والإطالة والتفضيل الذاتي، وبوابة شحن رقمية تُحدد قبل التشغيل.",
 trig_ar=["تقييم النموذج","اختبار البرومبت","eval","قياس الجودة","مقارنة نماذج"], trig_en=["llm eval","judge prompt","evaluation suite","benchmark prompts","regression test prompts","rubric"],
 pipeline=["المواصفة: ما المخرج الصحيح وما الذي يفوته المقياس.","شجرة الطريقة: مطابقة دقيقة ← قواعد ← قاضٍ نموذجي ← بشري؛ الأرخص الذي يكفي.","القاضي: معايير مسمّاة بمستويات مثبّتة بأمثلة، وحكم منظم + سبب، ونموذج مثبّت الإصدار.","المعايرة: اتفاق مع البشر على 30 عينة، وفحص تبديل الموضع، وتحيز الطول.","حجم العينة الكافي وبوابة الشحن الرقمية قبل التشغيل، ثم التقرير."],
 gates=["الرقم محسوب بالكود لا مقدّر.","القاضي لا يقيّم مخرجات نموذجه نفسه بلا فحص.","بوابة الشحن معلنة قبل رؤية النتائج."],
 outputs=["eval-spec.md","judge-prompt.md","dataset.jsonl","report.md"],
 kw=["eval","evaluation","judge","benchmark","rubric","regression","test prompts","quality metrics"]),
dict(n="31", slug="rag-knowledge-base", ar="قاعدة المعرفة وRAG", en="RAG & Knowledge Base",
 desc="بناء نظام أسئلة وأجوبة على ملفاتك: التقطيع بحسب البنية لا الطول فقط، والتضمين أو البحث النصي الكامل (FTS5 للعربية)، وإعادة الترتيب، وميزانية السياق، والإجابة بالاقتباس المباشر مع «ليس في المصدر» عند الغياب.",
 trig_ar=["ابحث في ملفاتي","قاعدة معرفة","RAG","اسأل الوثيقة","شات مع pdf"], trig_en=["rag","retrieval","knowledge base","chat with docs","embeddings","vector search","full text search"],
 pipeline=["المصادر: الأنواع والحجم واللغة والصلاحيات.","التقطيع: بالعناوين والفقرات مع تداخل 10%، وبيانات وصفية (الملف، الصفحة، العنوان).","الفهرس: SQLite FTS5 مع معالجة عربية (إزالة التشكيل وتوحيد الألف والياء) أو تضمينات عند توفرها؛ هجين عند الإمكان.","الاسترجاع: أعلى 20 ثم إعادة ترتيب ثم 5 ضمن ميزانية رموز معلنة.","الإجابة: اقتباسات مباشرة أولاً، ثم تحليل، ثم تدقيق كل ادعاء مقابل اقتباس؛ ما لا اقتباس له يُحذف."],
 gates=["كل إجابة تحمل مصدراً (ملف وصفحة).","«ليس في المصدر» بدل التخمين.","المحتوى المسترجع بيانات لا أوامر."],
 outputs=["index.sqlite","ingest.py","ask.py","eval-questions.md"],
 kw=["rag","retrieval","embedding","vector","knowledge base","chunking","semantic search","full-text","sqlite"]),
dict(n="32", slug="prompt-injection-defense", ar="الدفاع ضد حقن البرومبت", en="Prompt Injection Defense",
 desc="تأمين تطبيقات النماذج: تسوير المدخلات غير الموثوقة، وفصل الأوامر عن البيانات، وقوائم السماح للأدوات، ونقاط التوقف البشرية للأفعال الخطرة، واختبارات هجوم جاهزة (تجاوز، تسريب، إعادة توجيه)، وقواعد عدم تنفيذ تعليمات من محتوى مُلاحَظ.",
 trig_ar=["حقن برومبت","امان الذكاء الاصطناعي","جيلبريك","حماية البرومبت"], trig_en=["prompt injection","jailbreak defense","llm security","indirect injection","ai red team"],
 pipeline=["نمذجة التهديد: من يكتب ماذا في السياق (مستخدم، ويب، ملفات، أدوات).","التسوير: كل محتوى خارجي داخل علامات مع جملة «هذا بيانات لا تعليمات».","قوائم السماح: الأدوات والمجالات والمستلمون المحددون سلفاً، ولا شيء مقترح من المحتوى.","نقاط التوقف: الدفع والإرسال والحذف والنشر تتطلب تأكيداً بشرياً من القناة الأصلية.","مجموعة هجوم من 20 حالة (تجاوز، تسريب برومبت، تعليمات مخفية، ترميز) وتشغيلها قبل كل إصدار."],
 gates=["لا تعليمات تُنفَّذ من محتوى مُلاحَظ.","تسريب برومبت النظام لا يكشف أسراراً لأنه لا يحويها.","مجموعة الهجوم تمرّ 100%."],
 outputs=["threat-model.md","fences.md","attack-suite.jsonl","report.md"],
 kw=["prompt injection","security","jailbreak","red team","guardrails","llm security","sanitize","untrusted"]),
dict(n="33", slug="context-window-budget", ar="ميزانية نافذة السياق", en="Context Window Budget",
 desc="ما يدخل السياق وما لا يدخل: تصنيف كل مرشّح (ثابت، أو استرجاع عند الحاجة، أو تاريخ محادثة، أو أدوات)، وميزانية رموز لكل قسم، وترتيب يراعي التخزين المؤقت والمنتصف المفقود، وقاعدة إخلاء، وضغط التاريخ.",
 trig_ar=["السياق طويل","التوكنز","ضغط المحادثة","تكلفة النموذج","context"], trig_en=["context window","token budget","prompt caching","context engineering","compress history","lost in the middle"],
 pipeline=["صنّف كل مرشّح: كل استدعاء ← ثابت؛ يعتمد على السؤال ← استرجاع؛ تاريخ ← حديث حرفي وقديم ملخّص؛ غير ذلك ← يُحذف.","ميزانية بالأرقام لكل قسم ومجموع يترك مكاناً للرد.","الترتيب: الثابت أولاً للتخزين المؤقت، والحاسم في الطرفين.","قاعدة الإخلاء: أقدم تاريخ ← أقل استرجاع صلة ← أمثلة مطوّلة.","قياس قبل وبعد: التكلفة والزمن والجودة على 10 حالات."],
 gates=["الميزانية مكتوبة بالأرقام.","لا زيادة سياق بلا دليل تحسّن.","الضغط لا يفقد قرارات المستخدم."],
 outputs=["context-budget.md","eviction-policy.md","before-after.md"],
 kw=["context window","token","caching","context engineering","summarize history","memory","compaction"]),
dict(n="34", slug="few-shot-dataset-curation", ar="تنسيق الأمثلة ومجموعات البيانات", en="Few-Shot & Dataset Curation",
 desc="أمثلة ومجموعات تدريب وتقييم عالية الجودة: اختيار الأمثلة المتنوعة المطابقة للصيغة تماماً، وتغطية الحالات الحرجة، وإزالة التكرار والتسرّب، وتوازن الفئات، وتنسيق JSONL لـ fine-tuning والتقييم، وبطاقة بيانات.",
 trig_ar=["امثلة للبرومبت","داتاسيت","بيانات تدريب","few shot","fine tuning"], trig_en=["few-shot examples","dataset curation","training data","jsonl dataset","fine-tune data","example selection"],
 pipeline=["حدّد الهدف: أمثلة داخل البرومبت (3 إلى 5) أم مجموعة ضبط دقيق (مئات).","التنوع: كل مثال يغطي حالة مختلفة (عادي، حرج، فارغ، طويل، لغة مختلطة).","المطابقة: كل مثال بنفس صيغة الإخراج المطلوبة تماماً.","التنظيف: إزالة التكرار والتسرّب بين التدريب والتقييم، وفحص الحساسية (أسماء، أرقام هواتف).","بطاقة البيانات: المصدر، والترخيص، والتوزيع، والحدود المعروفة."],
 gates=["لا مثال يناقض القيود.","لا تداخل بين التدريب والتقييم.","لا بيانات شخصية بلا إذن."],
 outputs=["examples.md","train.jsonl / eval.jsonl","datacard.md"],
 kw=["few-shot","dataset","fine-tune","training data","jsonl","examples","synthetic data","labeling"]),
dict(n="35", slug="custom-gpt-claude-project", ar="بناء GPT مخصص ومشروع Claude", en="Custom GPT & Claude Project Builder",
 desc="يحوّل أي مهارة أو خبرة إلى مساعد قابل للنشر: تعليمات GPT (≤8000 حرف) مع ملفات معرفة وActions بـ OpenAPI، أو مشروع Claude بتعليمات ومهارات مرفوعة، مع مبادئ المحادثة، وأسئلة البداية، وخطة الاختبار.",
 trig_ar=["GPT مخصص","مشروع كلاود","اعمل مساعد","بوت","custom gpt"], trig_en=["custom gpt","claude project","build an assistant","gpt actions","openapi action","chatbot persona"],
 pipeline=["النطاق: ما يفعله المساعد وما لا يفعله، وجمهوره.","التعليمات عبر system-prompt-architect ضمن الحدود (8000 حرف لـ GPT).","ملفات المعرفة: مقسّمة بعناوين واضحة، وأقل من 20 ملفاً، وبلا أسرار.","Actions: OpenAPI 3.1 بوصف واضح لكل عملية ومصادقة Bearer؛ لا نقاط نهاية HTTP مكشوفة.","4 أسئلة بداية واختبار 10 محادثات منها 2 عدائية."],
 gates=["لا مفاتيح في التعليمات أو المعرفة.","Actions على HTTPS فقط.","الرفض لطيف ومحدد."],
 outputs=["instructions.md","knowledge/","openapi.json","starters.md","test-plan.md"],
 kw=["custom gpt","gpt builder","claude project","openapi","actions","assistant","chatbot"]),
dict(n="36", slug="excel-power-formulas", ar="إكسل: الصيغ والقوة", en="Excel Power Formulas",
 desc="حل أي مشكلة إكسل: صيغ حديثة (XLOOKUP، FILTER، LET، LAMBDA، SUMIFS)، وجداول منظّمة، وتنسيق شرطي، والتحقق من البيانات، وتصحيح الأخطاء (#N/A و#REF)، ودعم العربية والتواريخ الهجرية، مع ملف .xlsx جاهز مولّد بـ openpyxl ومفحوص بإعادة الحساب.",
 trig_ar=["اكسل","صيغة اكسل","جدول اكسل","xlookup","دالة"], trig_en=["excel formula","spreadsheet","xlookup","sumifs","excel help","xlsx"],
 pipeline=["افهم البيانات: الأعمدة والأنواع والأخطاء الشائعة (أرقام كنص، تواريخ كنص).","حوّل النطاقات إلى جداول منظّمة بأسماء ذات معنى.","الصيغة الأبسط التي تعمل: XLOOKUP بدل VLOOKUP، وSUMIFS بدل الصفيف، وLET للوضوح.","التحقق: scripts/xlsx_check.py يفتح الملف ويفحص الصيغ المكسورة والمراجع الدائرية والقيم الفارغة.","التسليم: ملف .xlsx بالصيغ (لا قيم ثابتة) + ورقة «كيف يعمل» بالعربية."],
 gates=["لا أرقام مكتوبة يدوياً حيث تنفع صيغة.","كل صيغة تُقرأ وتُفسَّر بجملة.","الملف يُفتح بلا أخطاء إصلاح."],
 outputs=["workbook.xlsx","formulas-explained.md"],
 kw=["excel","spreadsheet","xlsx","excel formula","openpyxl","pivot","vlookup","xlookup","google sheets"], scripts=True),
dict(n="37", slug="excel-financial-models", ar="النماذج المالية في إكسل", en="Excel Financial Models",
 desc="نماذج مالية احترافية: التدفقات النقدية المخصومة (DCF)، والموازنة والتوقع، وتحليل التباين، وتحليل الحساسية بجداول البيانات، وقواعد التنسيق (أزرق للمدخلات، أسود للصيغ)، وفحص الاتساق (الميزانية تتوازن) بالكود.",
 trig_ar=["نموذج مالي","DCF","موازنة","توقعات مالية","تحليل التباين"], trig_en=["financial model","dcf","budget model","variance analysis","sensitivity table","forecast model"],
 pipeline=["البنية: أوراق منفصلة للافتراضات والحسابات والمخرجات والفحوص.","الافتراضات بالأزرق في مكان واحد، وكل الحسابات تشير إليها.","النموذج: الإيرادات ← التكاليف ← EBITDA ← الضرائب ← التدفق الحر ← الخصم ← القيمة النهائية.","الحساسية: جدول ثنائي (معدل الخصم × النمو) وتحليل السيناريوهات.","فحوص آلية: الميزانية تتوازن، ولا قيم سالبة غير منطقية، والمجاميع تطابق."],
 gates=["لا رقم مدفون داخل صيغة.","ورقة الفحوص كلها «OK».","كل افتراض له مصدر أو تبرير."],
 outputs=["model.xlsx","assumptions.md","checks-report.md"],
 kw=["financial model","dcf","valuation","budget","forecast","excel","variance","lbo","cash flow"]),
dict(n="38", slug="excel-data-cleaning-automation", ar="تنظيف البيانات وأتمتة إكسل", en="Excel Data Cleaning & Automation",
 desc="تحويل ملفات إكسل الفوضوية إلى بيانات نظيفة: إزالة التكرار، وتوحيد الأسماء والتواريخ والأرقام العربية/الإنجليزية، ودمج أوراق متعددة، وPower Query أو Python/pandas، وأتمتة التقارير الدورية بسكربت واحد قابل للتكرار.",
 trig_ar=["نظف البيانات","دمج ملفات اكسل","تكرار","بيانات فوضوية","اتمتة اكسل"], trig_en=["clean excel data","merge spreadsheets","dedupe","data cleaning","automate excel report","pandas excel"],
 pipeline=["تشخيص: الأعمدة، والأنواع، والفراغات، والتكرار، والأرقام العربية، والتواريخ المختلطة.","قواعد التوحيد مكتوبة قبل التنفيذ (الاسم الكامل، الهاتف، التاريخ ISO).","التنفيذ بـ pandas أو Power Query مع سجل لكل تغيير (قبل/بعد، عدد الصفوف).","التحقق: المجاميع قبل وبعد، وعينة عشوائية 20 صفاً تُراجع.","سكربت قابل لإعادة التشغيل على الملف الجديد كل شهر."],
 gates=["لا حذف بلا سجل.","المجاميع المالية متطابقة قبل وبعد.","السكربت يعمل على ملف جديد بلا تعديل."],
 outputs=["clean.xlsx","cleaning-log.md","clean.py"],
 kw=["data cleaning","excel","pandas","power query","dedupe","etl","csv","merge","automation"]),
dict(n="39", slug="word-documents-pro", ar="مستندات وورد الاحترافية", en="Word Documents Pro",
 desc="مستندات Word كاملة التنسيق: أنماط عناوين، وجدول محتويات آلي، وترقيم، وجداول، وترويسات، واتجاه RTL صحيح للعربية مع خطوط مناسبة، وتعقّب التغييرات والتعليقات، وقوالب (تقرير، عقد، خطاب، سيرة) مولّدة بـ python-docx أو docx.js.",
 trig_ar=["وورد","ملف وورد","تقرير وورد","docx","خطاب رسمي","تنسيق مستند"], trig_en=["word document","docx","format document","report template","letter template","track changes"],
 pipeline=["البنية أولاً: مخطط العناوين والأقسام قبل أي نص.","القالب: أنماط (Heading 1-3، Normal، Caption) وخط عربي (Traditional Arabic أو Cairo) واتجاه RTL للفقرات العربية.","المحتوى: كتابة أو تحويل من Markdown مع جداول وصور بتسميات.","التلقائيات: جدول محتويات، وترقيم صفحات، وترويسة بالشعار، وحقول التاريخ.","التحقق: فتح الملف وفحص الأنماط والاتجاه؛ تصدير PDF عند الطلب."],
 gates=["لا تنسيق يدوي حيث يوجد نمط.","الفقرات العربية RTL ومحاذاة يمين.","جدول المحتويات محدّث."],
 outputs=["document.docx","template.dotx","document.pdf"],
 kw=["docx","word","document","python-docx","report","template","letter","formatting","rtl"]),
dict(n="40", slug="powerpoint-decks", ar="عروض باوربوينت", en="PowerPoint Decks",
 desc="عروض تقديمية احترافية: بنية قصصية (مشكلة، رؤية، كيف، إثبات، طلب)، وشريحة واحدة لفكرة واحدة، وتصميم بشبكة وألوان الهوية، ورسوم بيانية صادقة، وملاحظات المتحدث، ومولّد pptx من Markdown مع فحص الفائض والتباين.",
 trig_ar=["بوربوينت","عرض تقديمي","شرائح","برزنتيشن","pptx"], trig_en=["powerpoint","slide deck","presentation","pptx","pitch deck slides"],
 pipeline=["القصة في 10 جمل؛ كل جملة شريحة.","العنوان خلاصة لا موضوع («الإيرادات نمت 40%» لا «الإيرادات»).","التصميم: شبكة 12 عموداً، وهامش 5%، وحجم 24pt فأكثر، وصورة أو رسم واحد لكل شريحة.","الرسوم من البيانات بالكود، والمصدر أسفل كل رسم.","توليد pptx (python-pptx أو pptxgenjs)، وفحص الفائض عن حدود الشريحة والتباين، وملاحظات المتحدث لكل شريحة."],
 gates=["لا أكثر من 6 أسطر في الشريحة.","كل رسم له مصدر.","الخط 24pt فأكثر في المحتوى."],
 outputs=["deck.pptx","outline.md","speaker-notes.md"],
 kw=["pptx","powerpoint","presentation","slides","deck","python-pptx","reveal.js","keynote"]),
dict(n="41", slug="google-workspace-automation", ar="أتمتة Google Workspace", en="Google Workspace Automation",
 desc="أتمتة Sheets وDocs وSlides وDrive وGmail: صيغ Sheets المتقدمة (QUERY، ARRAYFORMULA، IMPORTRANGE)، وApps Script للمهام المتكررة، وقوالب Docs بحقول، وتنظيم Drive، وقواعد Gmail، مع احترام الصلاحيات ونقاط التأكيد قبل أي إرسال.",
 trig_ar=["جوجل شيت","google sheets","apps script","جوجل درايف","اتمتة جوجل"], trig_en=["google sheets","apps script","google docs template","drive organize","gmail filter","workspace automation"],
 pipeline=["اختر الأداة: صيغة إن كانت تكفي، ثم Apps Script، ثم API.","Sheets: QUERY للتصفية والتجميع، وARRAYFORMULA بدل الملء اليدوي، وجداول محمية للمدخلات.","Apps Script: دالة واحدة لكل مهمة، ومشغّل زمني، وسجل أخطاء، ولا مفاتيح في الكود.","Docs/Slides: قالب بحقول {{اسم}} ودالة تعبئة من الجدول.","الاختبار على نسخة من البيانات، والتأكيد البشري قبل أي إرسال أو مشاركة."],
 gates=["لا إرسال بريد بلا تأكيد.","الصلاحيات أقل ما يلزم.","السكربت يسجّل ما فعل."],
 outputs=["formulas.md","Code.gs","template-doc.md"],
 kw=["google sheets","apps script","google docs","google drive","gmail","workspace","automation","formula"]),
dict(n="42", slug="pdf-forms-reports", ar="ملفات PDF: النماذج والتقارير", en="PDF Forms & Reports",
 desc="كل ما يخص PDF: استخراج النص والجداول، وOCR للممسوح (عربي وإنجليزي)، وتعبئة النماذج، والدمج والتقسيم والضغط والعلامة المائية، وتوليد تقارير PDF مصمّمة من HTML بخطوط عربية صحيحة، والتوقيع والتشفير.",
 trig_ar=["pdf","استخرج من pdf","ادمج pdf","نموذج pdf","تقرير pdf","ocr"], trig_en=["pdf extract","merge pdf","fill pdf form","pdf report","ocr pdf","compress pdf"],
 pipeline=["شخّص الملف: نصي أم ممسوح، ومحمي أم لا، وحجمه.","الاستخراج: pdfplumber للنص والجداول، وOCR (tesseract ara+eng) للممسوح مع تدوير الصفحات.","المعالجة: دمج/تقسيم/تدوير/ضغط/علامة مائية بـ pypdf أو qpdf مع التحقق من عدد الصفحات.","النماذج: قراءة الحقول وتعبئتها وتسطيحها.","التوليد: HTML بخط عربي ← PDF عبر Playwright أو WeasyPrint مع هوامش طباعة واتجاه RTL."],
 gates=["عدد الصفحات بعد الدمج = المجموع.","OCR مُراجع على عينة.","لا بيانات شخصية تُرسل لخدمة خارجية بلا إذن."],
 outputs=["output.pdf","extracted.md / tables.csv","report.html"],
 kw=["pdf","ocr","extract","merge","form","report","pypdf","ghostscript","tesseract"]),
dict(n="43", slug="office-prompts-library", ar="مكتبة برومبتات أوفيس", en="Office Prompts Library",
 desc="برومبتات جاهزة ومُفحوصة لـ Copilot وChatGPT وClaude داخل إكسل ووورد وباوربوينت وأوتلوك: تلخيص التقارير، وشرح الصيغ، وتوليد الجداول، وإعادة صياغة الرسائل، وبنية العروض، مع متغيرات {{}} وتعليمات التنسيق والقيود، بالعربية والإنجليزية.",
 trig_ar=["برومبت اكسل","برومبت وورد","برومبت copilot","برومبتات اوفيس","برومبت ايميل"], trig_en=["excel prompt","word prompt","copilot prompt","office prompts","email rewrite prompt","powerpoint prompt"],
 pipeline=["حدّد التطبيق والمهمة والمدخل (ملف، تحديد، رسالة).","القالب: الدور + المهمة + المدخل المسوّر + الصيغة + القيود + مثال.","متغيرات {{}} لكل ما يتغير مع قيم افتراضية.","لنت كل برومبت بـ prompt-master-pro، وتجربة على مدخل حقيقي.","المكتبة مرتبة بالتطبيق ثم المهمة، ونسخة عربية ونسخة إنجليزية."],
 gates=["كل برومبت له مثال مدخل ومخرج.","لا بيانات حساسة في الأمثلة.","الصيغة محددة بدقة (جدول بـ4 أعمدة…)."],
 outputs=["office-prompts.md","prompts.json"],
 kw=["prompt","excel","word","powerpoint","copilot","office","email","template","productivity"]),
dict(n="44", slug="dashboards-dataviz", ar="لوحات المعلومات والتصور البياني", en="Dashboards & Data Visualization",
 desc="لوحات معلومات ورسوم بيانية صادقة وأنيقة: اختيار الشكل من السؤال، ولوحة ألوان متاحة للجميع، ونفس النظام في الوضعين الفاتح والداكن، وبطاقات مؤشرات، وتفاعل (تلميحات، تصفية)، بـ HTML/Plotly/Chart.js أو Streamlit أو Excel.",
 trig_ar=["لوحة معلومات","داشبورد","رسم بياني","تصور بيانات","مؤشرات"], trig_en=["dashboard","chart","data visualization","kpi cards","plotly","streamlit dashboard"],
 pipeline=["الأسئلة التي تجيب عنها اللوحة (3 إلى 5) والجمهور وتردد التحديث.","لكل سؤال شكل: اتجاه = خط، مقارنة = أعمدة، توزيع = هيستوغرام، علاقة = نقاط؛ لا فطائر لأكثر من 3 فئات.","الألوان: لوحة فئوية مفحوصة لعمى الألوان، وتسلسلية للكميات، وتباين AA.","التخطيط: الأهم أعلى اليسار (أو اليمين في RTL)، وبطاقات مؤشرات ثم تفاصيل.","كل رقم محسوب بالكود من البيانات، والمصدر وتاريخ التحديث ظاهران."],
 gates=["المحاور تبدأ من صفر للأعمدة.","لا رسوم 3D ولا تأثيرات زائفة.","اللوحة تعمل في الوضع الداكن."],
 outputs=["dashboard.html أو app.py","charts.png","data-notes.md"],
 kw=["dashboard","chart","visualization","plotly","streamlit","d3","kpi","analytics","tableau","power bi"]),
dict(n="45", slug="sql-data-analysis", ar="SQL وتحليل البيانات", en="SQL & Data Analysis",
 desc="استعلامات SQL صحيحة وسريعة (PostgreSQL، MySQL، SQLite، BigQuery): من السؤال التجاري إلى CTEs واضحة، ودوال النوافذ، والفهارس، وشرح خطة التنفيذ، وتحليل بـ pandas مع كل رقم محسوب بالكود، وتقرير بالعربية.",
 trig_ar=["sql","استعلام","قاعدة بيانات","تحليل بيانات","كويري"], trig_en=["sql query","analyze data","window function","query optimization","pandas analysis","explain plan"],
 pipeline=["ترجم السؤال التجاري إلى تعريف دقيق (ما العميل النشط؟ أي فترة؟).","المخطط: الجداول والمفاتيح والأنواع قبل الكتابة.","CTEs مسمّاة لكل خطوة، ودوال النوافذ بدل الانضمام الذاتي، ولا SELECT *.","الأداء: EXPLAIN، وفهرس على أعمدة التصفية والانضمام، وتجنّب الدوال على الأعمدة المفهرسة.","التحقق: مجاميع ضابطة، وعدد الصفوف المتوقع، وعينة يدوية؛ ثم التقرير بالأرقام في جدول."],
 gates=["كل رقم في التقرير له استعلام.","لا تحذير من القسمة على صفر أو NULL.","الاستعلام يعمل على بيانات اختبار."],
 outputs=["queries.sql","analysis.ipynb أو analysis.py","report.md"],
 kw=["sql","postgres","mysql","sqlite","bigquery","query","pandas","analysis","data","window function"]),
dict(n="46", slug="web-scraping-automation", ar="جمع البيانات من الويب", en="Web Scraping & Automation",
 desc="جمع بيانات عامة من المواقع باحترام الشروط: فحص robots وشروط الاستخدام، وPlaywright أو requests+BeautifulSoup، والترقيم والانتظار اللطيف، والتخزين في CSV/SQLite، وإعادة التشغيل من نقطة التوقف، والتوقف عند تسجيل الدخول وCAPTCHA.",
 trig_ar=["اسحب بيانات","سكرابينج","جمع بيانات من موقع","scraping"], trig_en=["scrape","web scraping","crawl","extract data from website","playwright scraper"],
 pipeline=["الأهلية: robots.txt والشروط، وهل توجد API رسمية أفضل.","الاستكشاف: بنية الصفحة والمحددات الثابتة (data-*، aria) لا الأصناف المتغيرة.","السكربت: معدل لطيف (ثانية بين الطلبات)، وUser-Agent واضح، وإعادة المحاولة المحدودة.","التخزين التدريجي في SQLite مع مفتاح فريد لإعادة التشغيل بلا تكرار.","التحقق: عدد السجلات، والقيم الفارغة، وعينة مقابل الموقع."],
 gates=["لا تجاوز لتسجيل دخول أو CAPTCHA.","لا بيانات شخصية تُجمع بلا أساس.","معدل الطلبات لا يضر الموقع."],
 outputs=["scraper.py","data.sqlite / data.csv","run-log.md"],
 kw=["scraping","crawler","playwright","beautifulsoup","selenium","extract","automation","browser"]),
dict(n="47", slug="notebooks-python-analysis", ar="دفاتر Python للتحليل", en="Python Analysis Notebooks",
 desc="دفاتر Jupyter مرتبة للتحليل: تحميل وتنظيف واستكشاف ونمذجة بسيطة وتصور، بخلايا مسمّاة وبذور ثابتة وبيئة مثبّتة، وتصدير تقرير HTML/PDF، والتحويل إلى سكربت قابل للتشغيل.",
 trig_ar=["jupyter","نوتبوك","تحليل بايثون","pandas","استكشاف بيانات"], trig_en=["jupyter notebook","pandas analysis","eda","exploratory data analysis","python data"],
 pipeline=["الهدف وسؤال التحليل في الخلية الأولى.","التحميل مع التحقق من الأنواع والفراغات والتكرارات (جدول ملخص).","الاستكشاف: توزيعات، وعلاقات، وقيم شاذة؛ رسم واحد لكل سؤال.","النمذجة إن لزمت: خط أساس بسيط أولاً، وتقسيم تدريب/اختبار، ومقياس معلن.","الخلاصة بالأرقام، وتصدير HTML، وسكربت .py يعيد إنتاج النتائج."],
 gates=["البذور ثابتة والنتائج قابلة للتكرار.","لا خلايا تعتمد على ترتيب تنفيذ مختلف.","كل رقم في الخلاصة من خلية محسوبة."],
 outputs=["analysis.ipynb","analysis.py","report.html"],
 kw=["jupyter","notebook","pandas","numpy","matplotlib","eda","python","data science","scikit"]),
dict(n="48", slug="forecasting-probability", ar="التوقع والاحتمالات", en="Forecasting & Probability",
 desc="تقدير «ما احتمال؟» بطريقة منضبطة: معدلات الأساس، وتحديث بايزي، والقيمة المتوقعة، وفترات الثقة، والسلاسل الزمنية البسيطة، وتحليل الحساسية، مع كل رقم محسوب بالكود ومعايرة الثقة.",
 trig_ar=["ما احتمال","توقع","احتمالية","تنبؤ","كم نسبة"], trig_en=["how likely","forecast","probability","bayesian","expected value","time series forecast"],
 pipeline=["صِغ السؤال بدقة قابلة للتحقق (ما، متى، بأي معيار).","معدل الأساس من فئة مرجعية، ثم التحديث بالأدلة المحددة.","احسب بالكود: التوزيع، والقيمة المتوقعة، وفترة 80%.","الحساسية: أي افتراض يغيّر القرار إن تغيّر 20%؟","الإخراج: الرقم مع الفترة، والافتراضات، وما يغيّر الرأي."],
 gates=["لا رقم بلا حساب.","الثقة معايرة لا مبالغ فيها.","الافتراضات معلنة."],
 outputs=["forecast.md","model.py","sensitivity.md"],
 kw=["forecast","probability","bayesian","statistics","time series","prediction","risk","monte carlo"]),
dict(n="49", slug="ab-testing-experiments", ar="اختبارات A/B والتجارب", en="A/B Testing & Experiments",
 desc="تصميم وتحليل التجارب: الفرضية والمقياس الأساسي، وحجم العينة بالقوة الإحصائية، والتوزيع العشوائي، ومدة التجربة، والتحليل (الفرق، وفترة الثقة، وp-value أو بايزي)، وأخطاء النظر المتكرر والمقاييس المتعددة.",
 trig_ar=["اختبار A/B","تجربة","حجم العينة","هل الفرق معنوي"], trig_en=["a/b test","experiment design","sample size","statistical significance","conversion test"],
 pipeline=["الفرضية: إن غيّرنا X فإن المقياس Y يتحسن بـ Z%.","المقياس الأساسي واحد، ومقاييس حماية (لا تتدهور).","حجم العينة بالكود من الأثر الأدنى والقوة 80% وألفا 5%.","التشغيل: توزيع عشوائي ثابت، ولا نظر مبكر، ومدة أسبوع كامل على الأقل.","التحليل بالكود وفترة الثقة، والقرار المعلن مسبقاً."],
 gates=["حجم العينة محسوب قبل البدء.","لا إيقاف مبكر بلا تصحيح.","القرار يتبع المقياس الأساسي."],
 outputs=["experiment-plan.md","sample_size.py","analysis.md"],
 kw=["a/b test","experiment","statistics","significance","conversion","growthbook","optimizely","hypothesis"]),
dict(n="50", slug="research-deep-citations", ar="البحث العميق بالمصادر", en="Deep Research with Citations",
 desc="بحث متعدد المصادر على أي موضوع: مصادر أولية بتواريخ، واقتباسات مباشرة، وأدلة متضاربة جنباً إلى جنب، وتصنيف كل ادعاء (مدعوم، متناقض، غير قابل للتحقق)، وملخص تنفيذي بالعربية مع قائمة مراجع.",
 trig_ar=["ابحث عن","بحث معمق","مصادر","ادلة","دراسة"], trig_en=["research","deep dive","sources","cite","literature review","fact check"],
 pipeline=["أسئلة البحث الثلاثة وحدود النطاق والتاريخ.","المصادر: أولية أولاً (وثائق رسمية، أوراق، بيانات)، ثم ثانوية؛ لكل مصدر التاريخ والناشر.","الاستخراج: اقتباسات مباشرة قصيرة مع الموقع، لا إعادة صياغة من الذاكرة.","التضارب: جدول يضع الأدلة المتعارضة جنباً إلى جنب وما يفسّر الفرق.","سجل الادعاءات: كل ادعاء بحالته ومصدره؛ ثم الملخص التنفيذي وما لم نستطع التحقق منه."],
 gates=["كل ادعاء له مصدر مؤرّخ أو يُعلَّم غير قابل للتحقق.","لا اقتباس أطول من 15 كلمة.","التواريخ مذكورة لكل حقيقة متغيرة."],
 outputs=["research.md","claims-ledger.md","references.md"],
 kw=["research","citation","sources","fact","evidence","literature","verify","web search","summary"]),
]
